### ISSUE TITLE
请问支持对Scala程序的问题诊断吗？

### ISSUE THREAD

**Issue by AlexKingSWU** [oldmanpushcart/greys-anatomy#100]
请问支持对Scala程序的问题诊断吗？

**Comment by oldmanpushcart** [comment]
Scala是基于JVM的产品，理论上所有基于JDK解释并运行的语言都能被Greys所支持，当然操作方式上可能略有不同。但由于我不是Scala的用户，所以是否能友好的交互以及如何更有好的交互，需要大家的帮忙。

**Comment by EdwardLee03** [comment]
@AlexKingSWU 支持Scala，我们在本地玩过
