### ISSUE TITLE
运行结果怎么保存到文件里？

### ISSUE THREAD

**Issue by trentsky** [oldmanpushcart/greys-anatomy#101]
运行结果怎么保存到文件里？

**Comment by muyuqiu001** [comment]
可以重写print方法，将内容不是通过TCP传输到控制台，而是直接到文件，同步写的话估计性能受比较大的影响

**Comment by oldmanpushcart** [comment]
不用哈，可以参考Greys的UserGuide中[其它问题](https://github.com/oldmanpushcart/greys-anatomy/wiki/greys-pdf#%E5%85%B6%E4%BB%96%E9%97%AE%E9%A2%98)
