### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by shrekwang** [oldmanpushcart/greys-anatomy#103]
start greys failed, because : com.sun.tools.attach.VirtualMachineDescriptor 
attach to target jvm(xxxx) failed.

java 环境为
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.2.el7_1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

服务器为阿里云ecs实列
cent os 7 操作系统

**Comment by shrekwang** [comment]
greys的版本为: Archive:  .greys/lib/temp_1.7.3.2_28120/greys-1.7.3.2-bin.zip

**Comment by oldmanpushcart** [comment]
1. 确保你执行greys的时候拥有和对映JVM拥有同样的权限哈
2. 确保你输入对了进程号，别输入成了其它的进程号（这条最有可能）

如果还不行，能否提供下现场的截图；

比如：

```
# 让我核对JVM进程
ps -ef | grep java
```

```
# 让我看到当前用户
who

# 让我看到你的启动参数
./greys.sh PID
```

**Comment by shrekwang** [comment]
为什么是who命令? who命令看到的用户确实和当前用户不一样, 因为我是先以其他账号登录, 然后su成其他用户的. 用whoami 命令看到的当前账号 和启动 java进程的账号一致.

**Comment by oldmanpushcart** [comment]
奇了怪了，能否给我一个现场看看，比如这台机器给我分配一个有对应权限的帐号？如果方便的话微博私信给我～

**Comment by shrekwang** [comment]
我自己找到问题了, 是JAVA_HOME设到JRE目录去了, 估计是tools.jar包找不到吧. 设置正确后就没问题了. 感谢回复.

**Comment by oldmanpushcart** [comment]
OK，看来我得想办法写一个检测脚本了...老是问人家要帐号不是个办法，哈哈
