### ISSUE TITLE
可以在打点命令运行的时候把控制台的输出存到日志文件吗？

### ISSUE THREAD

**Issue by garytao** [oldmanpushcart/greys-anatomy#106]
可以在打点命令运行的时候把控制台的输出存到日志文件吗？比如我执行ptrace命令，有的类被调用的很少，我要实时观察的话 很久才有调用一次，可不可以把观察到的结果输出到日志文件？

**Comment by oldmanpushcart** [comment]
1. Greys支持将信息输出到文件中么？

    支持，不过要做一些小命令。
    
    ```
    ./greys.sh 4567|tee -a ./greys.log
    ```

不知道这个是否能帮助到你

**Comment by garytao** [comment]
非常感谢，这样的话在启动greys时就产生了这个日志文件，我想再请教您一下，这个日志会记录我启动greys之后每次运行命令的结果吗？还是需要在运行命令时再次做一些处理？

**Comment by oldmanpushcart** [comment]
会记录下启动Greys之后所有信息，包括欢迎界面等
