### ISSUE TITLE
illegal ENV, please set $JAVA_HOME to JDK6+

### ISSUE THREAD

**Issue by edagarli** [oldmanpushcart/greys-anatomy#119]
echo $JAVA_HOME

show " /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home  "

why ?

**Comment by oldmanpushcart** [comment]
方便的话`java -version`，给我看看版本好么

**Comment by edagarli** [comment]
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by oldmanpushcart** [comment]
奇怪了，这个JDK版本在MACOS下经过测试了，没有问题才对。
能将你greys脚本之行的命令给我瞅下不，我看是否有`sudo -u`之类的前缀

**Comment by edagarli** [comment]
justhacker:greys justhacker$ sudo ./greys.sh 
illegal ENV, please set $JAVA_HOME to JDK6+

**Comment by oldmanpushcart** [comment]
哈哈哈，我知道了。

1. 如果你的应用是root启动的，可以这样

   ```
sudo -H ./greys.sh <PID>
```

1. 如果你的应用是admin启动的，可以这样

   ```
sudo -u admin -H ./greys.sh <PID>
```

1. 如果你的应用就是你当前用户`justhacker`启动的，可以这样

   ```
./greys.sh <PID>
```

**Comment by edagarli** [comment]
我可能需要再看看是否是其他原因～～   因为我是justhacker用户下启动./greys.sh <PID>的～

**Comment by Yaccc** [comment]
@oldmanpushcart 同样的问题

![image](https://cloud.githubusercontent.com/assets/5906306/19965007/eaafd614-a1ff-11e6-9a8e-775e4d68158f.png)
试了说的三种方法都不行，而且我目前就在自己的目录下

**Comment by Yaccc** [comment]
```shell
~/i-learn/greys/greys-anatomy/target/greys(branch:master) » echo $JAVA_HOME                        zhaodong@zhaodongdeMacBook-Pro
/Library/java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
```
 同样的问题，按照你的方法还是不能够解决，最终添加启动脚本的JAVA_HOME变量解决问题

**Comment by oldmanpushcart** [comment]
请问你的启动greys的命令是否通过了`sudo -u <LINUX_USER> -H ./greys.sh <PID>`这样的命令格式启动的呢？

**Comment by Yaccc** [comment]
@oldmanpushcart 不知道什么情况，我收到了github的notify。但是我在github pc竟然看不到你的那条回复了
是的,下面的命令我也执行过了，还是拿不到。所以我就改了greys.sh脚本手动加的
```shell
sudo -u admin -H ./greys.sh <PID>
```

**Comment by oldmanpushcart** [comment]
阿里公司最近访问github出现了点问题，估计我的信息发送失败了。我在Github回复的内容是：“能不能把你的运行环境给我看看呢”
我需要的信息是

1. 你执行的greys启动命令
2. 目标JVM启动的信息（ps -ef|grep java）
3. 目标JVM启动的用户是否和当前你登陆的用户保持一致？

**Comment by Yaccc** [comment]
哈哈，我以前也在阿里中间件实习来着呢~。大神,幸会幸会
1.greys 启动是。`./greys.sh pid`
2.目标JVM就是我的一个本地程序。用ps aux查看到时属于自己用户进程
![image](https://cloud.githubusercontent.com/assets/5906306/20055816/f163841c-a51d-11e6-8ea6-43c3d1e8edf5.png)
3. JVM信息
![image](https://cloud.githubusercontent.com/assets/5906306/20055868/44fda1ac-a51e-11e6-94be-503c81f64dc4.png)
4.java_home
![image](https://cloud.githubusercontent.com/assets/5906306/20055906/6e05921c-a51e-11e6-9d2c-782b08f3aa62.png)

**Comment by edagarli** [comment]
@Yaccc   其实我也是脚本添加路径解决的。因为线上环境不同，所以这种方式我不用考虑差异性
