### ISSUE TITLE
如何跟踪容器启动时代码

### ISSUE THREAD

**Issue by odd2008** [oldmanpushcart/greys-anatomy#128]
您好，
    请问当我在web容器启动的时候，就监控到相关信息应该怎么做呢？

**Comment by oldmanpushcart** [comment]
这个我还在想办法开发，之前都是为了运行时动态加载而设计的。启动就加载的设计我需要重新修改内核，时间比较漫长。但我会想办法支持的。

**Comment by muyuqiu001** [comment]
@odd2008 你想监控什么信息？

**Comment by muyuqiu001** [comment]
@oldmanpushcart 使用agent的话是否能够追踪到？

**Comment by yagumoreg** [comment]
有一个变通方法，开启目标进程debug，指定suspend=y，使目标进程拉起后马上挂起，然后greys附着上去，最后用IDE连接debug端口使目标进行跑进来。

**Comment by odd2008** [comment]
@muyuqiu001  非常感谢,使用agent是可以的
我最后还是使用了btrace

**Comment by oldmanpushcart** [comment]
@odd2008 等阿里内部的一个框架开源了，你的愿望就能实现了，目前我的greys2.0也是基于这个框架进行开发。

**Comment by oldmanpushcart** [comment]
#177 在2.0中支持掉
