### ISSUE TITLE
测试增加命令疑问，请回复

### ISSUE THREAD

**Issue by rodbate** [oldmanpushcart/greys-anatomy#130]
当我增加一个命令时，本地开发环境可用，而上传到服务器后这个命令就不见了，怎么
@oldmanpushcart

**Comment by rodbate** [comment]
![image](https://cloud.githubusercontent.com/assets/14209157/15570371/52eb6c64-2368-11e6-92f2-c2a06c551a91.png)这是本地windows环境

![image](https://cloud.githubusercontent.com/assets/14209157/15570418/898776b4-2368-11e6-9c96-4e2b12b6aa79.png) 这是linux环境，新增的topthread命令没有，求答复

@oldmanpushcart

**Comment by oldmanpushcart** [comment]
哇哈，windows下你的启动脚本解决了？求贡献`bat`  or `power shell`脚本；`topthread`也求贡献～～

一般是两个原因

1. 远程服务器的greys没有`shutdown`

   解决：登录上去后，执行命令`shutdown`，然后重连

2. 远程服务器没有进行安装成功

    因为本地安装脚本`install-local.sh`有一个蛋疼的逻辑

    ```
# install to local if necessary
if [[ ! -x ${GREYS_LIB_HOME} ]]; then

    # install to local
    mkdir -p ${GREYS_LIB_HOME} \
    || exit_on_err 1 "create target directory ${GREYS_LIB_HOME} failed."

    # copy jar files
    cp *.jar ${GREYS_LIB_HOME}/

    # make it -x
    # chmod +x ./greys.sh

fi
    ```

   如果你当前的版本和本地已经安装的版本，版本号一致，将不会进行安装；

   解决：修改version文件，让版本号抬高或降低；或者主动删除掉`${HOME}/.greys/lib`下对应的版本目录
