### ISSUE TITLE
illegal ENV, please set $JAVA_HOME to JDK6+

### ISSUE THREAD

**Issue by realczm** [oldmanpushcart/greys-anatomy#131]
[root@vps real]# ./greys.sh 30544
illegal ENV, please set $JAVA_HOME to JDK6+
[root@vps real]# echo $JAVA_HOME
/home/real/jdk1.8.0_51/bin/java
[root@vps real]# java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

help!

**Comment by Yaccc** [comment]
@realczm 请问你是怎么解决的呢

**Comment by realczm** [comment]
@Yaccc 忘记具体怎么处理，当时本机有1.6,1.7,1.8，应该是把其他版本卸载，保留1.7。你试试吧。

**Comment by Yaccc** [comment]
@realczm 我强行修改了greys脚本里面的JAVA_HOME解决了，我本地机器只有1.7！不知道什么问题
