### ISSUE TITLE
well-known file is not secure

### ISSUE THREAD

**Issue by ranqiqiang** [oldmanpushcart/greys-anatomy#139]
$ ./greys.sh 4421
start greys failed, because : well-known file is not secure
attach to target jvm(4421) failed.

JDK：/java/jdk1.7.0_79

从哪儿 可以找原因哦

**Comment by oldmanpushcart** [comment]
哦，这个你可以参考下网上的解决方案哦：[为什么会"well-known file is not secure" ?](http://lkf520java.iteye.com/blog/1560686)
