### ISSUE TITLE
【求助】远程安装   只能下载到greys.sh文件

### ISSUE THREAD

**Issue by whdxhw** [oldmanpushcart/greys-anatomy#141]
![image](https://cloud.githubusercontent.com/assets/20715036/17234975/f333fa5e-556f-11e6-87f9-0e0c5c7d1739.png)

直接找sh文件中的jar也未找到

**Comment by oldmanpushcart** [comment]
啊，就一个`greys.sh`就足够了，这个脚本在`运行的过程`中会自动下载最新版本的jar包，放在$HOME/.greys/lib/下边
