### ISSUE TITLE
greys 启动问题

### ISSUE THREAD

**Issue by yab** [oldmanpushcart/greys-anatomy#143]
1，第一次通过 greys.sh 19234启动 greys，启动正常
2，quit 退出后，再次启动greys.sh 32131，发现进入的还是原来的19234虚拟机（通过 jvm 命令查看的）
3，执行shutdown
4，再次 greys.sh 19234 一直卡住不动

jvm 版本：
SPEC-NAME : Java Virtual Machine Specification
SPEC-VENDOR : Oracle Corporation
SPEC-VERSION : 1.8
VM-NAME : Java HotSpot(TM) 64-Bit Server VM
VM-VENDOR : Oracle Corporation
VM-VERSION : 25.40-b25

**Comment by oldmanpushcart** [comment]
```
quit 退出后，再次启动greys.sh 32131，发现进入的还是原来的19234虚拟机
```
这个的原因是greys默认访问的是3658端口，原有的19234进程用的是quit命令退出，不会关闭端口，所以在此访问的仍然还是`19234`进程，直到shutdown命令关闭端口为止。


```
再次 greys.sh 19234 一直卡住不动
```

这个需要查下原因才行，有可能是19234进程启动greys失败（需要看19234的默认日志中greys的日志输出）；另外一种情况可能是3658端口被其他应用占用，试试`telnet 127.0.0.1 3658`
