### ISSUE TITLE
如何获取到Field的值

### ISSUE THREAD

**Issue by gcxtx** [oldmanpushcart/greys-anatomy#147]
public Object getField(String fieldName) throws NoSuchFieldException, IllegalAccessException {

            Field field = ownertarget.getClass().getDeclaredField(fieldName);
            boolean isaccess = field.isAccessible();
            field.setAccessible(true);
            Object returnField = field.get(ownertarget);

            field.setAccessible(isaccess);
            return returnField;
        }
获得到的Field对象的值是null的，不知道为啥。

if(advice.getClazz().getName().equals("org.apache.catalina.connector.Request")){
                                            GaField.FieldInvoke fileinvoke = new GaField.FieldInvoke(advice.target);
                                            Object returnFiled = fileinvoke.getField("localPort");
                                            printer.print("localPort returnobj :"+returnFiled.toString()+"\n");
                                        }

**Comment by oldmanpushcart** [comment]
```
if(advice.getClazz().getName().equals("org.apache.catalina.connector.Request")){
    GaField.FieldInvoke fileinvoke = new GaField.FieldInvoke(advice.target);
    Object returnFiled = fileinvoke.getField("localPort");
    printer.print("localPort returnobj :"+returnFiled.toString()+"\n");
}
```

你是自己实现了一个Command么？

**Comment by gcxtx** [comment]
嗯，是啊，我想获得到某个对象的字段内容，但是获得到的结果是空的不知道为什么啊。ownertarget是advice.target

**Comment by oldmanpushcart** [comment]
可以通过 #96 调试下你写的代码，从代码上看我没看出什么明显的错误哈

**Comment by gcxtx** [comment]
按照#96给出的方法配置完了，调试不了
![image](https://cloud.githubusercontent.com/assets/19422304/18985126/f219b5b0-8728-11e6-8c04-35214e7042e3.png)
![image](https://cloud.githubusercontent.com/assets/19422304/18985206/6ef3cc1a-8729-11e6-8856-1f683cd426df.png)
大牛帮忙看看怎么回事

**Comment by oldmanpushcart** [comment]
`DEBUG_MODE`这个JVM配置不是加在greys的启动程序上的，而是加在目标JVM启动参数中

**Comment by gcxtx** [comment]
搞定了，多谢大牛啦。
