### ISSUE TITLE
如何获取到tomcat的Request对象

### ISSUE THREAD

**Issue by gcxtx** [oldmanpushcart/greys-anatomy#148]
想获取到tomcat的Request对象，自己写了段代码如下所示：
```
 if(advice.getClazz().getName().equals("org.apache.catalina.connector.Request")&&advice.getMethod().getName().equals("getParameterValues")) {
                                            Request request = (Request)advice.target;
                                            printer.print(request.getContext().toString());
}
```
按照kun总的方法调试发现Request request = (Request)advice.target;抛出异常了，如下所示：
![image](https://cloud.githubusercontent.com/assets/19422304/19211009/149529e8-8d65-11e6-9c90-53faa24f1ded.png)
这是为什么呢，求大神解惑啊。

**Comment by oldmanpushcart** [comment]
因为他们两个的ClassLoader不是同一个，`advice.target`所得到的`request`，他的Class来自于Tomcat的ClassLoader，而你在代码中这样写，`Request`的类来自于Greys的ClassLoader；两者是不一样的
