### ISSUE TITLE
greys 查找不到 elasticSearch 插件类

### ISSUE THREAD

**Issue by fywxin** [oldmanpushcart/greys-anatomy#150]
elasticSearch ： 1.5.2
plugins： elasticsearch-sql-1.4.5

执行命令：
sc org.nlpcn.es4sql*

返回空~

**Comment by oldmanpushcart** [comment]
因为greys只能查询到已经加载到JVM的类，elasticSearch插件的类很可能没有被调用到，所以没有被JVM加载到任何一个ClassLoader，所以查询不到
