### ISSUE TITLE
怎么查找到对象 static 静态属性的值

### ISSUE THREAD

**Issue by fywxin** [oldmanpushcart/greys-anatomy#153]
watch com.cyou.fz.soa.log.dao.kafka.KafkaRpcLogConsumer consumerMessage target -x 1
只能获取到 对象的值， 如果要获取KafkaRpcLogConsumer类的静态属性值，该怎么获取呢？

private static long lastInsertTime = System.currentTimeMillis();

**Comment by oldmanpushcart** [comment]
```
watch *KafkaRpcLogConsumer consumerMessage target.lastInsertTime
```

试试呢？

其实

```
sc -df *KafkaRpcLogConsumer
```

也能看到
