### ISSUE TITLE
咨询: 通过greys能不能查询指定线程的所有ThreadLocal变量

### ISSUE THREAD

**Issue by luozengbin** [oldmanpushcart/greys-anatomy#154]
在共通类或者第三方java类（例如log4j MDC变量）使用ThreadLocal存储上下文参数是很常见到的场景。
但是如果没有正确清理存储在ThreadLocal中的变量可能导致Web应用重新部署时，旧的ClassLoader无法释放，进而导致旧版本Class无法释放造成方法区内存爆满。

针对这类问题的排查，如果可以快速dump出线程中所有ThreadLocal的内容的话会事半功倍。
不知道greys有没有这样的功能呢？

**Comment by oldmanpushcart** [comment]
这种场景，我基本上都会用jmap直接dump内存来得直接，你觉得呢？

**Comment by luozengbin** [comment]
因为greys很好用，想说如果能在线上立刻查出来的话，一定很cool !

**Comment by oldmanpushcart** [comment]
哈哈，感谢你的肯定。不过我一直尽量避免greys变成一个万能的工具，那就失去了我的初衷。不过我正在重新设计greys，开放他动态AOP的能力，让更多的人能写插件动态集成进来。
