### ISSUE TITLE
WatchCommand.java#L35 有误

### ISSUE THREAD

**Issue by dshdata** [oldmanpushcart/greys-anatomy#156]
`watch *StringUtils isBlank params[0] '#cost>100' `
并不能起效，因为没有强行指定b/f/e/s中的任何一个时，则默认为b，而invokeCost对象是在before()中初始化startTime的，并立即进行isInCondition判断，所以#cost永远是0。唯一有效的方式是加上f/e/s中任何一个，例如：
`watch -f *StringUtils isBlank params[0] '#cost>100'`

**Comment by oldmanpushcart** [comment]
这个略尴尬，的确是的，我周末想办法fix了

**Comment by oldmanpushcart** [comment]
我艸，不好修，你有什么好的建议么？

**Comment by dshdata** [comment]
我想在文档上补注一下就好了，cost变量语义上就是应该和-f搭配使用的
