### ISSUE TITLE
如何区分重载方法

### ISSUE THREAD

**Issue by yagumoreg** [oldmanpushcart/greys-anatomy#159]
我想对于有condition-express的命令，可以通过入参的数量、类型判断来规避，有没有更简单的方法？
另外monitor没有condition-express又怎么搞？

**Comment by yagumoreg** [comment]
第1个问题已在https://github.com/oldmanpushcart/greys-anatomy/issues/145找到了答案。

**Comment by oldmanpushcart** [comment]
`monitor`命令对于重载的方法，目前是不区分的，主要的难点还是在交互体验上，我没有想好一个比较优雅的方式交互

**Comment by cyberdak** [comment]
能想到最标准的方式就是采用 class 文件里面的入参格式来做就行了.

I[JB 就是代表 (int[] ,long ,byte)

**Comment by oldmanpushcart** [comment]
`I[JB`很明显，这个要被吐槽死的节奏，哈哈
