### ISSUE TITLE
非正常退出后原来增强的指令还会存在么?

### ISSUE THREAD

**Issue by zhenchuan** [oldmanpushcart/greys-anatomy#164]
如下,我使用watch命令来监控输入参数, 非正常退出(没有调用shutdown)
这样的话是不是这个监视会一直存在呢? 如果是,怎么清除呢?
```
watch -b *Dao extractDaily params[0]
```

我这边观察到的现象是监视似乎还在,因为我的每个请求的响应时间变长了

**Comment by oldmanpushcart** [comment]
- 如果是非正常退出，增强的代码是不会清除的；
- 正常的操作是执行`reset`+`quit`命令
- `shutdown` = `reset` + `quit`

**Comment by zhenchuan** [comment]
@oldmanpushcart ,多谢,
但是我怎么处理这种异常问题呢? 重启应用?

**Comment by oldmanpushcart** [comment]
重新连接一次greys，执行`reset`或者`shutdown`命令即可

**Comment by zhenchuan** [comment]
多谢啦,
