### ISSUE TITLE
能否统计某个方法的占用cpu情况

### ISSUE THREAD

**Issue by mwei83** [oldmanpushcart/greys-anatomy#168]
感谢，刚利用greys排查了一个问题。请问下，能否统计某个方法的占用cpu情况

**Comment by oldmanpushcart** [comment]
HI，

首先呢，我不打算利用greys定位性能问题，因为有比greys更专业的工具，比如jprofiler，命令行的有perfj。

其次，greys的确也做不准这件事哈。

greys的核心定位是帮助JAVA程序员去定位线上业务的疑难杂症，并不用来通用性的解决性能问题。

**Comment by oldmanpushcart** [comment]
HI，

首先呢，我不打算利用greys定位性能问题，因为有比greys更专业的工具，比如jprofiler，命令行的有perfj。

其次，greys的确也做不准这件事哈。

greys的核心定位是帮助JAVA程序员去定位线上业务的疑难杂症，并不用来通用性的解决性能问题。
