### ISSUE TITLE
如何获取tomcat中Request、Response对象

### ISSUE THREAD

**Issue by gcxtx** [oldmanpushcart/greys-anatomy#169]
之前提过一个问题“如何获取到tomcat的Request对象”，由于advice.target和greys-core不是一个classloader所以强转的时候会报错。尝试了很多办法，但总是不成功。现在有个需求就是要获取到tomcat里边的Request、Response对象，各位大牛有没有办法可以获取到呢。感激不尽！
自己写了段代码如下所示：

 if(advice.getClazz().getName().equals("org.apache.catalina.connector.Request")&&advice.getMethod().getName().equals("getParameterValues")) {
                                            Request request = (Request)advice.target;
                                            printer.print(request.getContext().toString());
}

**Comment by oldmanpushcart** [comment]
这个`Request`是不能直接这样强转的，因为它们的ClassLoader不一样，你只能通过反射的方式来调用他

**Comment by gcxtx** [comment]
多谢啦，已经搞定了。

**Comment by gcxtx** [comment]
以为搞定了，结果并没有。。
我重写了spy()这个函数，代码如下：
 public static Class<?> spyClassToClassloader(final ClassLoader targetClassLoader, String spyClassName)
            throws IOException, NoSuchMethodException, IllegalAccessException, InvocationTargetException {
        // 如果对方是bootstrap就算了
        if (null == targetClassLoader) {
            return null;
        }
        // Enhancer类只可能从greysClassLoader中加载
        // 所以找他要ClassLoader是靠谱的
        // 从目标ClassLoader中尝试加载或定义ClassLoader
        Class<?> spyClassFromTargetClassLoader = null;
        try {
            // 去目标类加载器中找下是否已经存在间谍
            // 如果间谍已经存在就算了
            spyClassFromTargetClassLoader = targetClassLoader.loadClass(spyClassName);
            //logger.info("Spy already in targetClassLoader : " + targetClassLoader);
        }
        // 看来间谍不存在啊
        catch (ClassNotFoundException cnfe) {

            try {// 在目标类加载起中混入间谍
                spyClassFromTargetClassLoader = defineClass(
                        targetClassLoader,
                        spyClassName,
                        toByteArray(Enhancer.class.getResourceAsStream("/" + spyClassName.replace('.', '/') + ".class"))
                );
            } catch (InvocationTargetException ite) {
                if (ite.getCause() instanceof java.lang.LinkageError) {
                    // CloudEngine 由于 loadClass 不到,会导致 java.lang.LinkageError: loader (instance of  com/alipay/cloudengine/extensions/equinox/KernelAceClassLoader): attempted  duplicate class definition for name: "com/taobao/arthas/core/advisor/Spy"
                    // 这里尝试忽略
                    //logger.debug("resolve #112 issues", ite);
                } else {
                    throw ite;
                }
            }
        }
        // 无论从哪里取到spyClass，都需要重新初始化一次
        // 用以兼容重新加载的场景
        // 当然，这样做会给渲染的过程带来一定的性能开销，不过能简化编码复杂度
        finally {
            return spyClassFromTargetClassLoader;
        }
    }
然后添加了一个类代码如下
public class TomcatRPInterceptor {
    public static Request httpRequest ;
    public static Request getHttpRequest() {
        return httpRequest;
    }
    public static void setHttpRequest(Request httpRequest) {
        TomcatRPInterceptor.httpRequest = httpRequest;
    }
}

最后在watchcommand里调用
if(advice.getClazz().getName().equals("org.apache.catalina.connector.Request")&& advice.getMethod().getName().equals("getParameterValues")){
                                            Class <?> definedClassLoader = spyClassToClassloader(advice.loader, TomcatRPInterceptor.class.getName());
                                            if (null == definedClassLoader) {
                                                return;
                                            }
                                            invokeStaticMethod(
                                                    definedClassLoader,
                                                    "setHttpRequest",
                                                    advice.target
                                            );
                                        }

使用invokeStaticMethod方法执行setHttpRequest方法，可以成功获取到Request对象，但是调用httpRequest对象的时候却是null的。。请问这个要怎么才能获取到Request 对象啊。

![image](https://cloud.githubusercontent.com/assets/19422304/21956118/2af7dca2-dab4-11e6-9cd5-91e8b7e2e511.png)
![image](https://cloud.githubusercontent.com/assets/19422304/21956120/33ac2df8-dab4-11e6-90b3-05156cd85c09.png)

**Comment by oldmanpushcart** [comment]
能把你的这部分代码邮件发送给我么？<oldmanpushcart@gmail.com>，或者如果你觉得需要实时沟通，也可以添加我的微博<http://weibo.com/vlinux>私信我
