### ISSUE TITLE
用greys monitor或trace时，经常会把主进程搞挂

### ISSUE THREAD

**Issue by suxiaoyong** [oldmanpushcart/greys-anatomy#170]
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f1300004050, pid=32738, tid=139706833803008

 JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  0x00007f1300004050

**Comment by oldmanpushcart** [comment]
哇哈，首先表示抱歉，不过能把JVM击溃的情况我还的确很少见，一般是JVM自身的BUG引起。因为JVM有非常强的鲁棒性。

你的错误勾起了我的好奇，能否提供下以下信息

1. `greys`版本

    可以通过`version`命令获取

1. 执行的命令，最关键的我希望能看到(`c-cnt`和`m-cnt`)

1. greys的`monitor`命令执行之后，JVM的表现是立即崩溃还是坚持了一段时间才崩溃。如果是后者，我希望能看到此时GC的情况`jstat -gccause PID 1000`

**Comment by suxiaoyong** [comment]
1. greys 版本：  1.7.6.4

2. 执行的命令：
```
ga?>watch -x 3 -f *AAAService method  params[0]
Press Ctrl+D to abort.
Affect(class-cnt:2 , method-cnt:2) cost in 196 ms.

ga?>ptrace *AAAService method -n 20
Press Ctrl+D to abort.
Affect(class-cnt:2 , method-cnt:129) cost in 330 ms.
```
3. 执行命令后，过了一段时间jvm崩溃，jvm崩溃时greys已经退出，感觉跟具体的命令关系不大。

4. coredump确实不方便提供，抱歉。

我试着换个jvm版本试试。

另外我们的代码都经过aspectj加强，这个是否会有影响。

**Comment by oldmanpushcart** [comment]
崩溃的`error_msg`能给我下么？
