### ISSUE TITLE
以后是否会支持局部变量

### ISSUE THREAD

**Issue by odd2008** [oldmanpushcart/greys-anatomy#172]
这个工作非常不错，不过对于线上诊断时，有时因为一些原因。
比如：IDEA工具需要单独安装，生产环境是安全桌面之类的同时使用eclipse默认的远程debug太慢了，很多时候，访问网络这些没有问题，使用eclipse默认的远程debug过了vpn之后太慢。
所以想请问您是否在后期考虑支持局部变量的查看？？
时间大概会在哪个周期？
谢谢。

**Comment by oldmanpushcart** [comment]
局部变量可以是可以，但我至今没有想好一个好的交互方式，太难了。你有什么好的建议？或者你期望中局部变量的交互方式应该是怎样的？

**Comment by odd2008** [comment]
我目前想的是很简单的，指定好具体类的之后和行号
就把当前的行的局部变量的值在输出出来
对于一行里面有多条语句的，则把所有的赋值语句的变量显示出来。

**Comment by oldmanpushcart** [comment]
@odd2008 明白了，有点类似IDEA在DEBUG时候的提示

**Comment by ccqy66** [comment]
这个提议很好，不知道实现上可行吗？有几个问题不知道可以解决不？
1.如果知道第几行有多少个变量，变量是什么？
2.如何确定变量在操作数栈的位置？
想了一种比较简单的方法，我想知道第n行的变量var1，那么就在第n+1行回调我的方法，把var1传出来。
但是目前找不到方法可以在原字节上任一行添加一行字节码？不知道作者是怎么想的？

**Comment by michaelssss** [comment]
类似idea的watcher那种功能，能够设定变量名，然后遇上了就回调特殊方法。这种操作我觉得很自然

**Comment by ccqy66** [comment]
这种方法理解上来说是可行的，但是到具体实现上有几个我目前没有办法想到的问题，也想请教一下：
1.“然后遇上了就回调特殊方法”，怎么算是遇到？
2.怎么定位到这个局部变量？

**Comment by oldmanpushcart** [comment]
这个不难，难得的我想弄明白你们要这个做什么？

**Comment by odd2008** [comment]
@oldmanpushcart  正如我上述的原因：
1.IDEA工具需要单独安装麻烦
2.生产环境在堡垒机后面，需要做debug，idea无法直接debug
3.idea可以通过网络连接上目标程序，但由于网络原因实在太慢

**Comment by oldmanpushcart** [comment]
@odd2008 如果真的需要做这种debug，而且不怕阻塞线上业务的话，可以用jdb命令
