### ISSUE TITLE
入参时有多个对象，想让每个对象分别按层级展开，可以做到吗？

### ISSUE THREAD

**Issue by chinamcafee** [oldmanpushcart/greys-anatomy#174]
watch -b com.xxx.yyy calculate params[0] -x 1  是可行的，但是如果入参有多个，请问如何写命令？

**Comment by oldmanpushcart** [comment]
试试
`watch -b com.xxx.yyy calculate params -x 1`

**Comment by chinamcafee** [comment]
多谢多谢，另外请问2.0的进度如何了？方便透露一下吗

**Comment by oldmanpushcart** [comment]
#177 在这里我统一回答好了

**Comment by chinamcafee** [comment]
辛苦了，您的工具为我们帮助良多，小小打赏，不成敬意~
