### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by liboyue23** [oldmanpushcart/greys-anatomy#175]
#./greys.sh 14706
new version(1.7.6.4) detection, update now...
######################################################################## 100.0%
Archive:  /root/.greys/lib/temp_1.7.6.4_14994/greys-1.7.6.4-bin.zip
   creating: /root/.greys/lib/temp_1.7.6.4_14994/greys/
  inflating: /root/.greys/lib/temp_1.7.6.4_14994/greys/ga.sh
  inflating: /root/.greys/lib/temp_1.7.6.4_14994/greys/greys-agent.jar
  inflating: /root/.greys/lib/temp_1.7.6.4_14994/greys/greys-core.jar
  inflating: /root/.greys/lib/temp_1.7.6.4_14994/greys/greys.sh
  inflating: /root/.greys/lib/temp_1.7.6.4_14994/greys/gs.sh
  inflating: /root/.greys/lib/temp_1.7.6.4_14994/greys/install-local.sh
update completed.
start greys failed, because : Unable to open socket file: target process not responding or HotSpot VM not loaded
attach to target jvm(14706) failed.

**Comment by oldmanpushcart** [comment]
HI 看看这个[FAQ](https://github.com/oldmanpushcart/greys-anatomy/wiki/FAQ)是否能帮助到你呢？
