### ISSUE TITLE
如何权衡一个类的加载是使用应用的ClassLoader还是AgentClassLoader

### ISSUE THREAD

**Issue by ccqy66** [oldmanpushcart/greys-anatomy#179]
最近在研究greys的代码。有一点不是很理解：
1.为什么要把greys-agent添加到BootstrapClassLoader,也就说下面的代码是什么作用：
 // 将Spy添加到BootstrapClassLoader
            inst.appendToBootstrapClassLoaderSearch(
                    new JarFile(AgentLauncher.class.getProtectionDomain().getCodeSource().getLocation().getFile())
            );
2.使用应用的ClassLoader加载greys中的类，能给我的应用带来怎样的问题？

非常感谢能够回答我的问题

**Comment by oldmanpushcart** [comment]
1. `greys-agent`添加到BootstrapClassLoader，是为了实现unsafe功能打开之后，你能用greys去观察JDK自带的类功能需要。比如`java.lang.String`、`java.io.PrintWriter`等。这些类是被BootstrapClassLoader所负责加载。

1. 使用应用的ClassLoader加载greys中的类

    这个理解是错误的，应用的ClassLoader和`AgentClassLoader`是相互隔离的，互相之间的类不会冲突和干扰

另外就是这个标题和内容，我没对应上哈。

**Comment by ccqy66** [comment]
"greys去观察JDK自带的类功能需要"这一句不是很理解，恳请解惑

**Comment by oldmanpushcart** [comment]
就是你能用greys去拦截、窥探来自BootstrapClassLoader所加载的类
