### ISSUE TITLE
oss token 失效

### ISSUE THREAD

**Issue by alwinlin23** [oldmanpushcart/greys-anatomy#180]
操作日期: 2017年03月01日

![image](https://cloud.githubusercontent.com/assets/2699243/23442321/af866048-fe62-11e6-8f5b-43aa2852a9eb.png)

**Comment by oldmanpushcart** [comment]
奇怪，能用呀，你用浏览器应该能直接打开[http://ompc.oss.aliyuncs.com/greys/install.sh](http://ompc.oss.aliyuncs.com/greys/install.sh)这个链接

**Comment by alwinlin23** [comment]
我刚才试了下,是可以的... issue closed 😂
