### ISSUE TITLE
卡住的进程可以查看调用的参数吗?

### ISSUE THREAD

**Issue by whitelilis** [oldmanpushcart/greys-anatomy#183]
对于重复调用的函数, 可以查看每次调用的参数或其它值.
对于卡住的进程, 它不动了, 有办法看到它正在调用的函数的参数吗? 
比如下面这个卡住了, 怎么看    te 这个函数的入参?

"main" #1 prio=5 os_prio=31 tid=0x00007fcf3a80b000 nid=0x1703 waiting on condition [0x0000700000219000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at SleepTest.te(SleepTest.java:3)
	at SleepTest.main(SleepTest.java:7)

**Comment by oldmanpushcart** [comment]
这个真不行，GREYS是要基于调用触发才能工作，DEBUG也是一样的原理。如果你真想看到挂起的线程中特定方法的入参，可以选择用jmap来dump当时内存的快照，反正也卡住了不是？

**Comment by whitelilis** [comment]
dump 出来能看到各种对象的个数和内存占用, 怎么看 入参 呢?

**Comment by oldmanpushcart** [comment]
ECLIPSE有个不错的工具叫mat，可以百度下哦

**Comment by Lihuanghe** [comment]
卡住的可以用jstack看线程调用栈啊

**Comment by whitelilis** [comment]
@Lihuanghe   我是想看 入参,  jstack 中是没有的

**Comment by oldmanpushcart** [comment]
的确，这个方法执行过了，这个入参的对象很可能已经被GC，谁任何工具事后都不能保证100%能看到了。

除非实现在目标方法上打点

**Comment by zhenghongfei** [comment]
这种情况应该是看不到入参了：jstack、jmap、mat都不行。

**Comment by vivisidea** [comment]
jmap dump 出来用 mat 进行线程分析可以看到参数的，之前有试过

**Comment by oldmanpushcart** [comment]
不能100%保证，如果这个方法已经被执行过了（不在堆栈路径中），同时正好一个GC，你就看不到了。我只能说概率你能看到
