### ISSUE TITLE
tt 命令的 -x 参数不起作用

### ISSUE THREAD

**Issue by whitelilis** [oldmanpushcart/greys-anatomy#184]
比如我用  tt -t -x 3 -n 1 -w params[2]  org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolClientSideTranslatorPB blockReceivedAndDeleted
得到的结果为
  PARAMETERS[2] | [Lorg.apache.hadoop.hdfs.server.protocol.StorageReceivedDeletedBlocks;@19ff4878

这是一个没有展开的结果.

而用 watch -x 3 -n 1 org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolClientSideTranslatorPB blockReceivedAndDeleted params[2]
得到的结果是
@StorageReceivedDeletedBlocks[][
    @StorageReceivedDeletedBlocks[
        storage=@DatanodeStorage[
            storageID=@String[DS-f014effd-46fe-44c5-bdbc-d30fee25d927],
            state=@State[NORMAL],
            storageType=@StorageType[DISK],
            STORAGE_ID_PREFIX=@String[DS-],
        ],
        blocks=@ReceivedDeletedBlockInfo[][
            @ReceivedDeletedBlockInfo[blk_2968775827_1905405058, status: RECEIVED_BLOCK, delHint: ],
        ],
    ],
]

这个结果才是想要的.
另外弱弱地问一下,   如果用  btrace 的话, 如何展开一个对象呢?

**Comment by whitelilis** [comment]
自己试出来用法了,  原来 -x 是在 -i 查看时用的....

**Comment by whitelilis** [comment]
不过还是想知道 btrace 怎么实现这样的功能, btrace 和 greys 之间切来切去, 好烦....

**Comment by whitelilis** [comment]
或者希望可以增加这样一个功能:
当执行到某个类某一行时,  执行  jstackAll(), 或者查看 local 变量, 或者查看函数相关的数据( advice 数据)

**Comment by oldmanpushcart** [comment]
等2.0吧，2.0的内核可以感知到行调用，其实在现在的greys中也能做到，但就看这件事的必要性。

如果你想看某一行的jstack，是否可以通过watch下一级调用的方法来实现。

我进行过很多年的线上问题定位，很少有场景是需要通过行来定位问题的。

**Comment by whitelilis** [comment]
感谢 @oldmanpushcart  ,   其实主要是用在分布式多线程的场景中, 有一些 interruptable lock, 中间做的事情太多, 有可能被其它线程打断, 而中间的函数调用, 出现的位置又特别多, 所以非常想知道, 执行到某一行时, 系统都在做什么,  特别是有没有其它线程会等待相应的锁, 这时用 行号就特别简单. 而平时用 debugger 的话, 主要也就是在某一行看当时的 local 变量和一些复杂的对象的内容

**Comment by oldmanpushcart** [comment]
嗯，不过我现在精力在完善GREYS2.0的内核上，估计得比较长的时间才能支持上这个功能。

你是否可以尝试PULL一个PATCH给我
