### ISSUE TITLE
bug:  tt 命令记录数超过 1700 后, 后面的会不可以见

### ISSUE THREAD

**Issue by whitelilis** [oldmanpushcart/greys-anatomy#185]
不使用 -n 参数,  当记录数超过 1700 之后, ctrl-D,   tt -l, 只看到  1300+ 个记录, 也就是说, 后面的记录都没有了.......

**Comment by oldmanpushcart** [comment]
在现有的GREYS中，tt命令是没有限制记录的数量的。你看到的应该是你的终端限制现实行数限制，实际上是真记录了1700+

要不你再核对下？

**Comment by whitelilis** [comment]
1, 实际上真是记录了 1700+
2, tt -l 确实显示不了那么多
3, tt -i 是可以看到特定记录的
4, 我调整了历史缓冲,  还是一样的,  tt -l  只能显示到    1067, 而实际上, 记录了 2078 条.

**Comment by oldmanpushcart** [comment]
-l只能到1067？真是个奇怪的数字，我有空试试

**Comment by oldmanpushcart** [comment]
亲，我亲测，在MAC的终端下，4000多个都是可以的哦
