### ISSUE TITLE
建议大神搞个图形界面，或者是web在线形式的图形界面

### ISSUE THREAD

**Issue by wangjia2016** [oldmanpushcart/greys-anatomy#186]
建议大神搞个图形界面，或者是web在线形式的图形界面

方便运维人员使用，哈哈 这样就无敌了。

**Comment by oldmanpushcart** [comment]
这个在2.0的规划中是通过开放协议的方式来支持。如果要做WEB端，需要牵扯网络隔离和集群注册的问题，这个只能是每个具体使用的场景自己去决策使用方式。

我还不如放开
