### ISSUE TITLE
trace命令突然失效(同样的参数)

### ISSUE THREAD

**Issue by orclight** [oldmanpushcart/greys-anatomy#188]
trace xx..xx..xx.className methodName

问题描述: 有2个问题
1.用greys的trace命令监控测试环境的方法执行，刚开始可以，后边突然就不行了。
2.测试环境开多个greys，greys trace命令能识别其他进程的的方法，不能识别自己进程的方法

前几次：
Affect(class-cnt:1 , method-cnt:1) cost in 63 ms.

最近一次：
Affect(class-cnt:0 , method-cnt:1) cost in 32 ms.

**Comment by oldmanpushcart** [comment]
1. trace命令对代码膨胀会比较厉害，所以多用几次就会让JVM抛出Code Too Large的异常，所以你可以用reset命令进行清理

1. trace命令能匹配其他进程的方法？这个没看明白，希望能得到更明确的描述

**Comment by orclight** [comment]
在一台linux服务器(centsos 6)，部署了多个Java进程(业务不一样)；用greys连接其中一个进程，

**Comment by oldmanpushcart** [comment]
不同进程下用端口号进行区分，所以你需要换个端口号。

```
./greys.sh PID@IP:PORT
```

**Comment by orclight** [comment]
端口加了，没有犯这个低级错误

**Comment by oldmanpushcart** [comment]
- 就看你是怎么退出的，如果是`quit`命令或者`CTRL_C`退出，目标JVM的3658端口是不会主动关闭的，直到你执行了`shutdown`命令为止。

- 目前是没有临时文件这个说法，只有历史命令用到了一个临时文件。

- 如果不确定，你可以用`jvm`命令来核对你是否greys对了正确的JVM进程

**Comment by lawulu** [comment]
这个应该写到FAQ里面啊。。
