### ISSUE TITLE
命令无法执行

### ISSUE THREAD

**Issue by HadesJK** [oldmanpushcart/greys-anatomy#189]
刚开始能执行的，不知道为啥，后来一直报命令执行失败，请看：

ga?>watch -b com.xx.xxx.xxxx saveGoodsEdit params[0]
Command execution failed. cause : class redefinition failed: attempted to delete a method

**Comment by oldmanpushcart** [comment]
这个是GREYS1.x架构的一个坑，因为GREYS会主动缓存住上次修改类的字节码内容，而我一开始设计的时候天真的认为所有类不会再进行改变。

但很明显，在遇到一些AOP类时，有可能会出现这些类被删除方法的尴尬情况。而JVM规定redefine类时候不允许出现方法被删除，所以会造成这个错误。

- 短期解决方案：遇到这种错误，执行`reset`命令，还原GREYS之前增强的类。
- 长期解决方案：在GREYS2.x版本之后（尚在开发内核），这个问题将会被彻底修复
