### ISSUE TITLE
请问下greys进度

### ISSUE THREAD

**Issue by windywang** [oldmanpushcart/greys-anatomy#193]
请问下作者，现在greys处于什么进度，因为本人非常喜欢这款作品，看到好久没有更新，如果作者工作比较忙，是否能借助团体力量，譬如牵头在网上召集志同道合的人一起来做。还有很希望能有一个统一的web入口可以查看

**Comment by oldmanpushcart** [comment]
非常感谢您的热情关注和肯定。GREYS目前足够满足需求而且也没有什么明显的BUG，所以保持一个稳定的发布版本，暂不做过多的改变。做多错多嘛。

一些细微的优化，比如 #146 、 #160 、 #190 、 #191 等几个issue，目前暂不影响主流程的正常使用，所以我也先暂时靠后。

我比较担心的是GREYS自身内核架构设计的缺陷。当前已经知道的缺陷有两个

1. GREYS无法和其他采用了`ClassFileTransformer`的框架正常协作。

    > 这个设计缺陷到目前一直没有人反馈。但我知道这个是一个很严重的问题，一旦发生将无法通过简单的架构调整进行修复。

2. UI渲染和业务流程处理混淆，不利于扩展。

    > greys-client只是一个非常简单的telnet客户端，甚至你都可以用telnet命令来取代他。所以你看到的所有表格的渲染都是在服务端完成，而且用的是宝贵的业务线程时间，在极端的情况下会导致业务处理出现比较严重的毛刺。最不能接受的是无法完成客户端的扩展（比如WEB客户端）

所以这段时间我都在想办法重构GREYS这款软件，想重新对他的功能进行一次定位。具体节奏可以参考 #177 ，当前已经完成内核的研发，这个内核是必须从阿里内部开源出来的，否则GREYS无法继续进行开源的研发。但走开源流程好慢好慢啊。

**Comment by oldmanpushcart** [comment]
这款软件之所以开源，目的其实有三个

1. 让使用者放心

    这个工具如果要进行排查问题，最终是要以一个非常高的权限跑在业务JVM上的。意味着他将会接管这个JVM进程所有的权限，能看到你DB的账号密码（如果你没做妥善处理的话），甚至能操作JVM／OS的在当前帐号下的所有行为。

    这么敏感的软件如果不开源，相信很多地方也不敢给你进行使用。所以开源所有代码也是希望使用者能放心。

1. 向同行业的兄弟产品分享我在这个领域的思考、设计和实现方式。

    诚然，我也不会是第一个想到这么去做的人。在我之前有BTrace、HouseMD两个产品都在往这个方向努力。我在设计这款软件的时候也从这两位前辈中得到了很多知识点。喝水不忘挖井人，我希望能将这份知识分享传承下去，做更多更好的工具，造福更多的Javaer。

1. 孵化更多的类似产品

    在阿里内部已经开始有技术产品是对标GREYS进行封装／研发，比如阿里中间件团队的arthas，在集团内部就有非常不做的口碑。

    GREYS的方法插桩方案、技巧，也帮助了一些团队在快速搭建他们产品上绕过了一些技术上的坑，少走了一些弯路。


回到你的问题，既然我有这份心开源，我也就希望开源社区能帮助到我。不求回馈于GREYS，但求能在你对GREYS不能完全满足你的需求，需要进行深度改造、甚至重做的时候，能稍微帮助、提示到你一点，我也很知足，很开心了。

最后，祝工作顺利。少用GREYS～ 👍
