### ISSUE TITLE
使用greys导致应用fullgc频率飙升（每秒一个）

### ISSUE THREAD

**Issue by wangchangshuai** [oldmanpushcart/greys-anatomy#194]
<html>
<body>
<p>
使用greys多次（最后一次使用tt命令拦截大量方法）后发生应用卡死现象，使用jstat发现应用fullgc频率非常高。
使用jhat分析发现：<font><color=red><b>com.github.ompc.greys.core.Advice@0x714459ad0 (85 bytes)和com.github.ompc.greys.core.Advice$1@0x723dd0660 (41 bytes)</color></b></font>这两个类分别有16万个对象，总计32w，明显是这个对象创建的太多了，并且一直被引用着，不释放，最后导致内存溢出；
</p>
<pre>
jstat -gcutil 23609 1000
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2345 1564.208 1621.658
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2346 1565.360 1622.811
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2348 1566.737 1624.187
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2348 1566.737 1624.187
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2349 1568.551 1626.001
  0.00 100.00 100.00  99.97  98.75  95.82   1888   57.450  2351 1569.943 1627.393
  0.00 100.00 100.00  99.97  98.75  95.82   1888   57.450  2351 1569.943 1627.393
  0.00 100.00 100.00  99.97  98.75  95.82   1888   57.450  2352 1571.537 1628.987
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2354 1572.934 1630.384
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2354 1572.934 1630.384
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2355 1574.515 1631.966
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2356 1575.947 1633.398
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2357 1576.164 1633.615
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2358 1577.725 1635.176
  0.00  99.99 100.00  99.97  98.75  95.82   1888   57.450  2359 1578.934 1636.385
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2360 1579.159 1636.610
  0.00 100.00 100.00 100.00  98.75  95.82   1888   57.450  2361 1580.787 1638.237
  0.00 100.00 100.00 100.00  98.75  95.82   1888   57.450  2361 1580.787 1638.237
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2363 1582.439 1639.890
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2363 1582.439 1639.890
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2364 1584.024 1641.475
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2365 1585.283 1642.733
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2367 1586.751 1644.201
  0.00 100.00 100.00  99.98  98.75  95.82   1888   57.450  2367 1586.751 1644.201
  0.00 100.00 100.00  99.99  98.75  95.82   1888   57.450  2368 1588.572 1646.023

</pre>

<p>
jmap -histo 23609 |head -100
</p>
<pre>
 num     #instances         #bytes  class name
----------------------------------------------
   1:        811585     3958799256  [C
   2:          8971       22204512  [B
   3:        809663       19431912  java.lang.String
   4:        170639       15016232  java.lang.reflect.Method
   5:        217095       11106048  [Ljava.lang.Object;
   6:        160710        8999760  com.github.ompc.greys.core.Advice
   7:        288430        6922320  java.util.concurrent.atomic.AtomicLong
   8:        171848        6873920  java.util.LinkedHashMap$Entry
   9:        165459        6618360  com.github.ompc.greys.core.advisor.ReflectAdviceListenerAdapter$2
  10:        160710        6428400  com.github.ompc.greys.core.TimeFragment
  11:        165459        5294688  com.github.ompc.greys.core.advisor.ReflectAdviceListenerAdapter$1
  12:        160710        5142720  com.github.ompc.greys.core.Advice$1
  13:        161088        3866112  java.util.Date
  14:        209470        3351520  java.lang.Integer
  15:         31557        3029472  java.util.jar.JarFile$JarFileEntry
  16:         71712        2868480  com.github.ompc.greys.core.textui.TTree$Node
  17:         80903        2588896  java.util.HashMap$Node
  18:        157176        2514816  com.github.ompc.greys.core.util.GaMethod$MethodImpl
  19:          7913        2320768  [Ljava.util.HashMap$Node;
  20:         83751        2010024  java.util.ArrayList
  21:          6989        1796752  [I
  22:         13654        1521048  java.lang.Class
  23:           561        1157904  [Ljava.util.concurrent.atomic.AtomicLong;
  24:         30223         967136  java.util.concurrent.ConcurrentHashMap$Node
  25:         10020         801600  java.lang.reflect.Constructor
  26:         12007         768448  java.net.URL
  27:         29133         466128  java.lang.Boolean
  28:          9515         456720  org.apache.catalina.loader.ResourceEntry
  29:          8766         420768  java.util.HashMap
  30:           421         329824  [Ljava.util.concurrent.ConcurrentHashMap$Node;
  31:          6595         263800  java.lang.ref.SoftReference
  32:          8171         261472  java.lang.ref.WeakReference
  33:          6810         217920  java.util.Hashtable$Entry
  34:          4070         212392  [Ljava.lang.String;
  35:          7777         186648  java.lang.Long
  36:          2806         179584  com.mysql.jdbc.ConnectionPropertiesImpl$BooleanConnectionProperty
  37:          3190         178640  java.util.LinkedHashMap
  38:          4230         169200  java.util.TreeMap$Entry
  39:          7648         162040  [Ljava.lang.Class;
  40:          2102         151344  java.lang.reflect.Field
  41:          3622         144880  java.util.WeakHashMap$Entry
  42:          4284         137088  java.lang.ThreadLocal$ThreadLocalMap$Entry
  43:          8243         131888  com.github.ompc.greys.core.util.GaMethod$ConstructorImpl
  44:          7116         113856  java.lang.Object
  45:           909         113152  [Ljava.util.Hashtable$Entry;
  46:          2250         108000  org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference
  47:          3748          89952  java.beans.MethodRef
  48:          3687          88488  java.lang.Double
  49:          1772          85056  org.aspectj.weaver.reflect.ShadowMatchImpl
  50:          3488          83712  com.github.ompc.greys.core.util.collection.ThreadUnsafeFixGaStack
  51:            35          82720  [Ljava.nio.channels.SelectionKey;
  52:          1942          77680  javax.servlet.jsp.tagext.TagAttributeInfo
  53:          1376          77056  org.apache.ibatis.mapping.ParameterMapping
  54:           110          76960  [Lio.netty.util.Recycler$DefaultHandle;
  55:           594          71280  com.mogujie.pay.regulation.infrastructure.shared.model.BusinessRule
  56:          1662          66480  com.sun.org.apache.xerces.internal.dom.DeferredTextImpl
  57:             2          65568  [Lcom.mogujie.trace.lurker.LurkerEvent;
  58:          1166          65296  java.beans.MethodDescriptor
  59:           989          63296  com.mysql.jdbc.ConnectionPropertiesImpl$StringConnectionProperty
  60:          2623          62952  java.lang.Class$AnnotationData
  61:            16          61696  [Ljava.nio.ByteBuffer;
  62:           897          57408  java.util.concurrent.ConcurrentHashMap
  63:          1772          56704  org.aspectj.weaver.patterns.ExposedState
  64:           968          54208  com.alibaba.druid.pool.DruidPooledConnection
  65:           750          54000  java.beans.PropertyDescriptor
  66:           299          53936  [Ljava.util.WeakHashMap$Entry;
  67:          1655          52960  java.util.LinkedList
  68:           931          52136  java.lang.Package
  69:           539          51744  org.springframework.beans.GenericTypeAwarePropertyDescriptor
  70:          1586          50752  java.util.concurrent.locks.ReentrantLock$NonfairSync
  71:           304          50304  [Ljava.lang.ThreadLocal$ThreadLocalMap$Entry;
  72:          1218          48720  com.sun.org.apache.xerces.internal.dom.DeferredAttrImpl
  73:          1006          48288  org.apache.velocity.runtime.parser.Token
  74:           128          48128  java.lang.Thread
  75:           667          42688  com.mysql.jdbc.ConnectionPropertiesImpl$IntegerConnectionProperty
  76:          1042          41680  com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr
  77:          1719          41256  java.util.jar.Attributes$Name
  78:           851          40848  org.apache.tomcat.util.modeler.AttributeInfo
  79:           847          40656  ch.qos.logback.classic.Logger
  80:           723          40488  com.sun.org.apache.xerces.internal.dom.DeferredElementImpl
  81:          1629          39096  com.mogujie.raptor.common.Pair$ImmutablePair
  82:          1188          38016  com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr
  83:          2315          37040  java.util.HashMap$EntrySet
  84:           761          36528  java.util.Hashtable
  85:           132          34848  com.mysql.jdbc.JDBC4PreparedStatement
  86:           133          33672  [[C
  87:          1400          33600  org.apache.ibatis.reflection.invoker.MethodInvoker
  88:          1356          32544  com.mogujie.raptor.monitor.MonitorKey
  89:          1342          32208  org.springframework.transaction.interceptor.AbstractFallbackTransactionAttributeSource$DefaultCacheKey
  90:           633          30384  java.util.concurrent.ConcurrentHashMap$TreeNode
  91:           755          30200  java.math.BigInteger
  92:          1210          29040  sun.reflect.generics.tree.SimpleClassTypeSignature
  93:           603          28944  org.apache.tomcat.util.digester.CallMethodRule
  94:          1159          27816  java.util.LinkedList$Node
  95:           193          27792  com.mysql.jdbc.Field
  96:            23          27784  com.mysql.jdbc.JDBC4Connection
  97:            13          26832  [Lorg.apache.ibatis.ognl.internal.Entry;
</pre>
</body>
<html>

**Comment by oldmanpushcart** [comment]
从jmap的输出来看，你应该是用了tt命令。tt命令会把方法的输入和输出都记录到内存中，如果任凭他记录下去，内存会耗尽。所以

1. 确保tt命令不要持有过多的记录
2. 用完之后请执行`tt -D`命令清理tt的记录

**Comment by wangchangshuai** [comment]
但是有个问题，我greys控制台已经退出了，为什么还在tt还在执行呢？

**Comment by oldmanpushcart** [comment]
你是不是用`CTRL+Z`停止的？

**Comment by wangchangshuai** [comment]
明白了，是ctrl+z。还有一个问题，有没有设计文档，比如软件的包说明，简单架构说明等

**Comment by oldmanpushcart** [comment]
这个项目是我个人业余时间写的，暂时还没那么完善的设计文档哦，非常抱歉～
