### ISSUE TITLE
tt 监听method及其子method的stack

### ISSUE THREAD

**Issue by ougyou** [oldmanpushcart/greys-anatomy#195]
tt只能监听到从底层到当前方法的堆栈及其出入参数
但如何监听整个方法链的堆栈信息呢，因为有的业务无法多次执行，
但是后续判断逻辑复杂，这样就没法去tt后面的动作。

想了下描述的是有问题的，其实是想知道tt listen的方法下的
方法代码的执行过程。

**Comment by oldmanpushcart** [comment]
首先抱歉下哈，最近工作有点小忙，很多问题答复都不及时了。
你的这个问题解法是这样的

1. `tt -p`

    `tt`命令是有重放功能的，利用这个功能你可以在另外一个终端中来回切换你真正想`tt`的细节。当然了，这样的排查手段适合于“可重复读”的场景。

2. `ptrace -t`

    如果想一次性跟踪到一次调用核心链路上不同节点的`tt`信息，可以用这个命令。这个命令中所记录的内容是和`tt`命令打通的。

    具体用法也可以看帮助文档哈[ptrace命令](https://github.com/oldmanpushcart/greys-anatomy/wiki/greys-pdf#ptrace命令)
