### ISSUE TITLE
greys 无法监听 package java.io 的资源情况？

### ISSUE THREAD

**Issue by zhenglincheng** [oldmanpushcart/greys-anatomy#202]
项目需要跟踪到jdk package 的一些资源情况，发现无法追踪到java.io 包

**Comment by AnyinSong** [comment]
@zhenglincheng 

https://github.com/oldmanpushcart/greys-anatomy/wiki/greys-pdf

### JDK类支持

JDK的类默认由BootstrapClassLoader负责加载，由于Greys自己也适用了大量的JDK类，所以我不建议使用Greys直接对JDK相关类进行增强、代理。

默认而言，Greys会拒绝执行关于JDK类的操作命令。你需显式用options命令打开。

```
ga?>options unsafe true
+--------+--------------+-------------+
| NAME   | BEFORE-VALUE | AFTER-VALUE |
+--------+--------------+-------------+
| unsafe | false        | true        |
+--------+--------------+-------------+
Affect(row-cnt:1) cost in 4 ms.
ga?>
```

**Comment by zhenglincheng** [comment]
Tks
