### ISSUE TITLE
greys的启动命令应该支持传入用户名和密码

### ISSUE THREAD

**Issue by AnyinSong** [oldmanpushcart/greys-anatomy#203]
当前启动命令只支持指定ip:port不支持传入用户名和密码，导致跨节点观测java进程功能可用性很低

**Comment by oldmanpushcart** [comment]
你是说安全性是吧

**Comment by AnyinSong** [comment]
NoNo，提出的初衷和安全没啥关系，而是因为目前我所在的环境情况是开发、生产所有节点都是有用户名和密码的，我想其他地方应该也是类似的，不要用户名和密码就能远程连接的节点应该很少吧，除非做了互信。 @oldmanpushcart

**Comment by oldmanpushcart** [comment]
因为走的是TELNET协议的简化版，所以忽略了用户名和密码的实现，因为觉得没有必要。从你的理由描述中也只是觉得`而是因为目前我所在的环境情况是开发、生产所有节点都是有用户名和密码的，我想其他地方应该也是类似的`应该要有，没有看到需要身份验证的必要性～

**Comment by AnyinSong** [comment]
我的问题其实是说远程节点连不上的问题，
我又研究了几遍说明文档，发现应该是对启动方式的说明让我产生了误解
```
启动Greys

参数说明

./greys.sh <PID>[@IP:PORT]
**PID：**目标Java进程ID（请确保执行当前执行命令的用户必须有足够的权限操作对应的Java进程）

**IP：**目标服务器IP地址，当远程服务开启之后，其他人可以通过指定IP的形式加载到对应目标机器的Java进程中，从而实现远程协助。专门用于解决目标主机账号没有权限，但对方兄弟却非常需要你支援的时候。Greys允许多个用户同时访问，并且各自的命令不会相互干扰执行。

**PORT：**目标服务器端口号，设计端口号的初心则是希望解决同台机器上存在多个Java进程需要被Greys分析的情况，默认的端口号是3658，如果不做区分则会引起端口冲突。

启动范例

如果不指定IP和PORT，默认是127.0.0.1和3658

./greys.sh 12345
等价于

./greys.sh 12345@127.0.0.1
等价于

./greys.sh 12356@127.0.0.1:3658
```

这段启动说明让人觉得指定pid@ip:port就可以像IDE的远程调试一样观察远程机器的jvm，但我试了很多此都不行，开始我以为是访问节点没有指定用户名和密码的原因，但后来我对照IDE远程调试的场景觉得需要在服务端启动greys才行，然后我再次看文档注意到了这段话：
```
多人并行协作

基于C/S架构的任务模式甚至能让多人同时远程到同一进程上执行不同的指令、脚本，非常适合团队一起进行线上问题排查与跟踪。Greys采用纯Java编写并留有良好的扩展，如果你有需求，只要你会Java，就可以为你自己编写想要的功能。 Greys最有利的武器是他的表达式，能让你在感受到HouseMD集成功能便利的同时，也能发挥出自定义Btrace脚本的灵活。
多人协作

应用管理员拥有JVM进程权限，由他来首先在目标JVM上启动Greys
技术专家A和B平时没有对应机器的权限，但只要网络能访问，他们可以通过指定ip:port直接访问目标机器的JVM进程，仿佛在本地一般
```
然后我就完全参照远程调试的配置形式，先在目标机器上启动了greys，然后在客户端机器是使用 ./greys.sh ip:port的方式连接目标机器上的greys发现成功了，这里不需要指定pid。

那么这里就有了一个新的疑问，启动服务端的greys就在目标机上为何需要指定ip？难道说就是为了直接连接远程jvm？让greys服务端和目标jvm还可以不在同一个节点上？

**Comment by oldmanpushcart** [comment]
因为GREYS是C/S架构，通过TCP协议保持通讯。

`./greys.sh 49521`
和
`./greys.sh 49521@127.0.0.1:3658`
和
`./greys.sh 49521@:3658`

三个命令的效果是一样的

**Comment by AnyinSong** [comment]
现在我已经基本都想通啦，只是因为对启动命令的说明未区分服务端和客户端让我一开始对用法产生了误解，现在关闭此issue
