### ISSUE TITLE
[建议]在Java 9环境中支持

### ISSUE THREAD

**Issue by YuhuiFeng** [oldmanpushcart/greys-anatomy#207]
在java 9环境下，由于jigsaw项目，许多jvm层面的API已作出的调整，比如说`sun.management.RuntimeImpl#getBootClassPath`，在JDK9中，永远会输出`UnsupportedOperationException`。因此在java 9环境中greys，`jvm`等查询都会失败。

由于2.0的新内核已经在开发中，不知道在2.0中是否有对JDK9的支持，能否透露下这方面的规划。

**Comment by oldmanpushcart** [comment]
哭……没有考虑JDK9，谁能帮我修啊，我还得参加双十一

**Comment by YuhuiFeng** [comment]
develop-2.0 是新内核的开发branch吗？发现里面仍然有许多阿里的内部API调用...

**Comment by oldmanpushcart** [comment]
是的，`develop-2.0`时新内核的开发branch，里面用的是阿里开源组件[jvm-sandbox](https://github.com/alibaba/JVM-Sandbox)，目前关于GREYS2.0对字节码增强部分的功能将会集中在jvm-sandbox上进行开发，GREYS自身的功能将会在`deveop-2.0`这个分支上实现。

**Comment by YuhuiFeng** [comment]
@oldmanpushcart  了解，请问server端如何debug？

**Comment by oldmanpushcart** [comment]
参考 #96 哈
