### ISSUE TITLE
[建议] 向gradle迁移

### ISSUE THREAD

**Issue by YuhuiFeng** [oldmanpushcart/greys-anatomy#211]
不知道，是否有这个打算，将maven替换成gradle？

好处是，可以把所有的打包和管理逻辑都放到build.gradle中，而且可以增加代码可读性。之所以考虑到这点事，想到对JDK9的支持上，势必需要添加由jdk9单独编译的模块。虽然maven也能做，但是不如gradle来得方便和直观

**Comment by oldmanpushcart** [comment]
非常不错的提议，但有几个现实中的困难。

1. 我个人对gradle不熟悉，greys中需要一些打包的技巧，从maven切换到gradle有一定的困难
2. 时间不够，目前在忙公司的双十一，真心没有时间
3. 和未来规划冲突，在未来规划中（GREYS2.0版本），将会采用[jvm-sandbox](https://github.com/alibaba/JVM-Sandbox)来实现字节码增强的内核。这个项目是我的妻子所发起，脱胎于greys，所以技术上同源质量也有保障。

**Comment by YuhuiFeng** [comment]
@oldmanpushcart 谢谢你的反馈，也了解情况。目前处于兴趣，我已经在master上自己写了一些东西。而之所以提出这个建议，是因为在实现对jigsaw的严格支持上，受到了maven的限制。目前进度

1. 基于 https://github.com/oldmanpushcart/greys-anatomy/pull/209，我已完成master上maven向gradle的完整迁移，但是因为不了你的观点，所以没有push出来。
2. 正在进行开发对jigsaw的严格支持。通过调研初步结论是应该不会对core的替换造成什么影响，所有的开发工作集中在agent模块中。

感谢你们对双十一的付出，我们可以之后再讨论这个问题

**Comment by YuhuiFeng** [comment]
想了下，之前的思路有点问题，core模块也需要做一些的修改。但是更多应该只是添加一层代理类（来增加模块相关操作），而不会影响其原有逻辑和功能

**Comment by oldmanpushcart** [comment]
我已经在`1.7.6.5`版本中整合了你提供的JDK9支持patch，目前测试在JDK9中工作正常，非常感谢。
maven切换成gradle的事情我打算先搁置一下，毕竟个人还是喜欢maven :)

**Comment by YuhuiFeng** [comment]
其实我在本地早就有gradle的迁移版本的patch了，但是因为我之前做了JDK9的小改动，gradle迁移patch是基于那个之上的，所以没有发布出来。

如果有兴趣，我可以发出来不合并。至于后续，我可以等2.0出来后，再看看能不能帮忙重新做迁移。

至于之前提到的JDK9的严格支持，我做了一部分开发，原理和基础框架部分已经出来。但是同样，因为目前主线是2.0开发，所以我暂且搁置了这部分的工作。

**Comment by oldmanpushcart** [comment]
好的，2.0我得加速了，目前只写了version命令，client一行代码都没写。

我看了也试用过gradle，还是没有理解他的好处，让我再想想，当然我懒也是一个主要原因，如果你能在2.0框架出来之后直接提供patch，我倒是乐意尝试。
