### ISSUE TITLE
windows下如何使用？想用ide把这个工程跟起来深入了解，做不到啊

### ISSUE THREAD

**Issue by zhenjia001** [oldmanpushcart/greys-anatomy#216]

**Comment by oldmanpushcart** [comment]
如果只是想调试，参考#96，但我还真不知道这么在windows下用😂

**Comment by zhenjia001** [comment]
非常感谢，要想断点agent的，需要远程连上监控目标的jvm（监控目标加上-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000），不是对greys进行远程调试。
继续学习

**Comment by zhenjia001** [comment]
windows下也可以使用，
修改一下AgentLauncher，把agentJar稍微改一下，不然在windows下总是获取不到对应agentjar路径
例如：  String agentJar = args.substring(0, index);
            final String agentArgs = args.substring(index, args.length());
            if("null".equals(agentJar)){
                String tmpAgent=args.substring(args.indexOf("greysAgent")+11,args.length());
                agentJar=tmpAgent.substring(0,tmpAgent.indexOf(";"));
            }
然后用ide启GreysLauncher ，配置参数-pid 7672 -target 127.0.0.1:3228 -agent greys-agent-jar-with-dependencies.jar
再启动GreysConsole
java  -cp greys-core-jar-with-dependencies.jar com.github.ompc.greys.core.GreysConsole 127.0.0.1 3228
这样就可以在windows下也能使用greys了。很强大，准备增加扩展能力，不知道@oldmanpushcart 能否建议一下，想做的是有个类有问题，动态修改（用正确的类方法）去替换

**Comment by zhenjia001** [comment]
JavaScript这部分是如何使用？使用场景是什么？请帮忙@oldmanpushcart

**Comment by oldmanpushcart** [comment]
@zhenjia001 在windows下改动的，提交下代码？哈哈

**Comment by zhenjia001** [comment]
@oldmanpushcart
好的，我完善一下就提交
谢谢，js我再研究一下。是可以动态把原来的类或者方法进行切面或者替换吗？看着挺高级，得深入研究一把了

**Comment by oldmanpushcart** [comment]
只做切面不做替换(虽然本质是把完成切面的类替换原有的类，但我担心你说的替换是HotSwap的机制)

greys所有的命令，理论上都可以用js重写一次，就是性能开销上会比较大

**Comment by zhenjia001** [comment]
是HotSwap的机制，性能开销会很大吗？我整个简单的压测一下
