### ISSUE TITLE
【建议】启动过程未安装unzip命令报错，考虑是否可以支持tar解压缩

### ISSUE THREAD

**Issue by coodoing** [oldmanpushcart/greys-anatomy#218]
./greys.sh 12345
new version(**1.7.6.4**) detection, update now...
###################################100.0%
./greys.sh: line 164: unzip: command not found
update fail, ignore this update.
Error: Unable to access jarfile /home/www/.greys/lib/**0.7.6.4**/greys/greys-core.jar
attach to target jvm(12345) failed.

1）这里是否能支持tar的解压缩方式？ 因为有些服务器可能没有安装unzip包执行不了unzip命令，但基本上都可以用tar命令。
2）更新失败后衍生的问题：通过get_local_version()方法获取路径异常，造成greys命令不能正常启动。这里是否考虑可以添加默认版本解决？

**Comment by oldmanpushcart** [comment]
1. 建议收到，我改改

2. 不建议加默认版本，理由如下

    1. 需要考虑到这台机器上从来没有安装过任何版本greys的情况
    2. 属于更新失败后的异常问题，而且如果这台机器曾经有过greys老版本，更新失败会让脚本使用老版本兼容掉这次错误

**Comment by oldmanpushcart** [comment]
在`1.7.6.5`版本中增加tar支持

**Comment by coodoing** [comment]
赞 速度
