### ISSUE TITLE
1.7.6.6安装失败

### ISSUE THREAD

**Issue by whitelilis** [oldmanpushcart/greys-anatomy#221]
![image](https://user-images.githubusercontent.com/1090230/33812472-abb112de-de58-11e7-886e-6051f6d5fdcf.png)

**Comment by whitelilis** [comment]
检查发现有这样一个文件  .greys/lib/temp_1.7.6.6_6378/greys-1.7.6.6-bin.zip

**Comment by oldmanpushcart** [comment]
好奇怪的错误，我希望能得到更多信息
1. greys 的安装方式
2. 执行命令command -v unzip

**Comment by whitelilis** [comment]
1, 安装方式是  curl -sLk http://ompc.oss.aliyuncs.com/greys/install.sh|sh   ,  因为之前安装过老版本, 所以之前执行了  rm -rf .greys greys.sh

2, command -v unzip 的输出是  /usr/bin/unzip

**Comment by oldmanpushcart** [comment]
非常抱歉，我知道问题出在哪里了...低级问题

https://github.com/oldmanpushcart/greys-anatomy/commit/d79a2fdfbf5df132e84fab6bb497ca5d703f1d86#diff-c2b2b6098611729cb9ba4e2cd1ad624d
