### ISSUE TITLE
入参返回值对象转json

### ISSUE THREAD

**Issue by zxiaofan** [oldmanpushcart/greys-anatomy#224]
监控入参返回值的时候支持将方法的入参or返回值对象转成json么，查了下文档和网上资料，没找到耶

**Comment by oldmanpushcart** [comment]
试试

```shell
options json-format true
```

**Comment by zxiaofan** [comment]
完美，Tks

**Comment by zxiaofan** [comment]
刚试了下，1、观察返回值控制台能打印json，比如watch -s *ServiceImpl queryHotelDetail returnObj -x 1；
2、但是观察入参却不能打印json，比如watch -b *ServiceImpl queryHotelDetail params[0];  这个的返回值依旧是对象，是还有什么需要注意的么

**Comment by oldmanpushcart** [comment]
不应该啊，除非这个对象被你拼接成字符串了。你完整的命令是上边贴出来的么？

用-x1可以给我看看params[0]大概是个啥？

**Comment by zxiaofan** [comment]
完整命令和返回结果如下：
----
第1次操作 params[0]
----

ga?>
ga?>options json-format true
+-------------+--------------+-------------+
| NAME        | BEFORE-VALUE | AFTER-VALUE |
+-------------+--------------+-------------+
| json-format | true         | true        |
+-------------+--------------+-------------+
ga?>watch -b *HotelServiceImpl queryHotelDetail '"params[0]="+params[0]'
Press Ctrl+D to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 306 ms.
params[0]=com.zxiaofan.common.Request@3111a6d
----
----
第2次操作 params[0] -x 1
----
----
ga?>options json-format true
+-------------+--------------+-------------+
| NAME        | BEFORE-VALUE | AFTER-VALUE |
+-------------+--------------+-------------+
| json-format | true         | true        |
+-------------+--------------+-------------+
ga?>watch -b *HotelServiceImpl queryHotelDetail '"params[0]="+params[0] -x 1'
Press Ctrl+D to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 320 ms.
Encountered " <INT_LITERAL> "1 "" at line 1, column 27.
Was expecting one of:
    <EOF> 
    "," ...
    "=" ...
    "?" ...
    "||" ...
    "or" ...
    "&&" ...
    "and" ...
    "|" ...
    "bor" ...
    "^" ...
    "xor" ...
    "&" ...
    "band" ...
    "==" ...
    "eq" ...
    "!=" ...
    "neq" ...
    "<" ...
    "lt" ...
    ">" ...
    "gt" ...
    "<=" ...
    "lte" ...
    ">=" ...
    "gte" ...
    "in" ...
    "not" ...
    "<<" ...
    "shl" ...
    ">>" ...
    "shr" ...
    ">>>" ...
    "ushr" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "%" ...
    "instanceof" ...
    "." ...
    "(" ...
    "[" ...
    <DYNAMIC_SUBSCRIPT> ...
    "(" ...

**Comment by oldmanpushcart** [comment]
问题出在你的表达式中
```
'"params[0]="+params[0]'
```

这样写表达式，GREYS是这样等价处理的
```
"params[0]="+params[0].toString()
```

所以正确的写法应该是
```
params[0]
```
