### ISSUE TITLE
希望增加一个 trace_life 的命令

### ISSUE THREAD

**Issue by whitelilis** [oldmanpushcart/greys-anatomy#236]
有时为了追踪内存泄漏，希望知道哪一个特定的类的对象的生命周期，比如
先在某个时间 <init> 了一个对象 a , 然后在某个时间，它被某个方法调用了一次，后来 xxxx
最后，被某一次 YGC 或 FGC 给回收了。
这样就展现了它的完整生命周期。
如果内存泄漏，则很有可能再也不会回收。

**Comment by oldmanpushcart** [comment]
针对内存内存泄漏的排查，最好的方式不应该是jmap命令dump下来么？
