### ISSUE TITLE
jdk8  tomcat8.5.16  greys1.7.6.6 启动失败

### ISSUE THREAD

**Issue by 287400117** [oldmanpushcart/greys-anatomy#245]
大神帮忙看下这是什么问题

```
[root@eshop.content.ms.01 greys]# ./greys.sh 7177
start greys failed, because : Unable to open socket file: target process not responding or HotSpot VM not loaded
attach to target jvm(7177) failed.
```

**Comment by garytao** [comment]
start greys failed, because : Unable to open socket file: target process not responding or HotSpot VM not loaded
attach to target jvm(8766) failed.

**Comment by garytao** [comment]
出现同样的错误

**Comment by garytao** [comment]
Server version: Apache Tomcat/7.0.57
Server built:   Nov 3 2014 08:39:16 UTC
Server number:  7.0.57.0
OS Name:        Linux
OS Version:     2.6.32-431.23.3.el6.x86_64
Architecture:   amd64
JVM Version:    1.6.0_45-b06
JVM Vendor:     Sun Microsystems Inc.

**Comment by oldmanpushcart** [comment]
@garytao 看下应用的主日志里面有什么信息哦？

**Comment by garytao** [comment]
"VM Thread" prio=10 tid=0x00007fbf3015f000 nid=0x224b runnable 

"Gang worker#0 (Parallel GC Threads)" prio=10 tid=0x00007fbf30019000 nid=0x2240 runnable 

"Gang worker#1 (Parallel GC Threads)" prio=10 tid=0x00007fbf3001a800 nid=0x2241 runnable 

"Gang worker#2 (Parallel GC Threads)" prio=10 tid=0x00007fbf3001c800 nid=0x2242 runnable 

"Gang worker#3 (Parallel GC Threads)" prio=10 tid=0x00007fbf3001e800 nid=0x2243 runnable 

"Gang worker#4 (Parallel GC Threads)" prio=10 tid=0x00007fbf30020000 nid=0x2244 runnable 

"Gang worker#5 (Parallel GC Threads)" prio=10 tid=0x00007fbf30022000 nid=0x2245 runnable 

"Gang worker#6 (Parallel GC Threads)" prio=10 tid=0x00007fbf30024000 nid=0x2246 runnable 

"Gang worker#7 (Parallel GC Threads)" prio=10 tid=0x00007fbf30025800 nid=0x2247 runnable 

"Concurrent Mark-Sweep GC Thread" prio=10 tid=0x00007fbf30119800 nid=0x224a runnable 
"Gang worker#0 (Parallel CMS Threads)" prio=10 tid=0x00007fbf30115800 nid=0x2248 runnable 

"Gang worker#1 (Parallel CMS Threads)" prio=10 tid=0x00007fbf30117000 nid=0x2249 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007fbf30277800 nid=0x225a waiting on condition 

JNI global references: 63928

Heap
 par new generation   total 2764800K, used 2022747K [0x0000000630000000, 0x00000006eb800000, 0x00000006eb800000)
  eden space 2457600K,  81% used [0x0000000630000000, 0x00000006aa4a97d8, 0x00000006c6000000)
  from space 307200K,   6% used [0x00000006c6000000, 0x00000006c72ad7c0, 0x00000006d8c00000)
  to   space 307200K,   0% used [0x00000006d8c00000, 0x00000006d8c00000, 0x00000006eb800000)
 concurrent mark-sweep generation total 4268032K, used 2703471K [0x00000006eb800000, 0x00000007f0000000, 0x00000007f0000000)
 concurrent-mark-sweep perm gen total 262144K, used 183206K [0x00000007f0000000, 0x0000000800000000, 0x0000000800000000)

**Comment by garytao** [comment]
@oldmanpushcart  一打点主日志 会有GC的 log，感觉是JVM 内存不够用

**Comment by garytao** [comment]
top - 09:42:08 up 305 days, 8 min, 13 users,  load average: 0.09, 0.02, 0.01
Tasks: 213 total,   1 running, 212 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.2%us,  0.4%sy,  0.0%ni, 99.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  16333788k total, 16120140k used,   213648k free,   476292k buffers
Swap:        0k total,        0k used,        0k free,  6342996k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                
 8766 admin     20   0 12.1g 7.9g  13m S  4.3 50.8 300:25.10 java

**Comment by garytao** [comment]
内存16G 都用光了

**Comment by garytao** [comment]
找到原因了，Java Pid 用admin 用户启动的，打点用的root用户，越权了。谢谢杜琨

**Comment by 287400117** [comment]
经过各种测试，最后发现是权限问题。运行 greys 的用户必须要跟 运行 Tomcat是同一个用户。

mark.. 记录一下，也能让碰到同样问题小伙伴少走弯路。
