### ISSUE TITLE
远程到目的主机的jvm吗？我试了不行

### ISSUE THREAD

**Issue by csgvsjay1000** [oldmanpushcart/greys-anatomy#253]
./greys.sh pid@remoteIp:port
可以远程到目的主机的jvm吗？我试了不行

**Comment by oldmanpushcart** [comment]
目标主机必须先本地启动greys

**Comment by csgvsjay1000** [comment]
哦，原来如此

**Comment by ccc520** [comment]
目标主机开了也不行，是我用的不对吗...
1).目标主机  ./greys.sh 111926
2).目标主机 开放3658端口
3.)远程主机 ./greys.sh 111926@10.1.5.137:3658

start greys failed, because : No such process
attach to target jvm(111926) failed.

telnet是能通的

jdk版本:1.8.0.172
greys版本:1.7.6.6

**Comment by oldmanpushcart** [comment]
@ccc520 可以通过加[:端口]解决

ga.sh完成attach的，gs.sh shutdown就好了
