### ISSUE TITLE
watch命令怎么支持同时打印param和returnObj，并且param和returnObj是复杂对象

### ISSUE THREAD

**Issue by qinzhengyan** [oldmanpushcart/greys-anatomy#258]
通常我们在定位问题的时候，肯定是希望一行里面同时打印入参和出参，
如果用param[0]+returnObj 就会是字符串拼接了，无法按照-x 参数对对象
进行展开，不能清楚看到对象中每个属性的值，麻烦指教。

**Comment by whitelilis** [comment]
这时我一般用  tt -t， 不用 watch

**Comment by qinzhengyan** [comment]
@whitelilis 非常感谢，这个场景果然适合用tt来解决，谢谢
