### ISSUE TITLE
please set $JAVA_HOME to JDK6+ ？I have done

### ISSUE THREAD

**Issue by wadekun** [oldmanpushcart/greys-anatomy#48]
如图：
![Uploading 8A81B36F-7B4C-40EC-83C1-C3FA3BA6E0F8.png…]()

 我已经设置了java_home，且jdk版本为1.7，不知是什么原因呢。

**Comment by wadekun** [comment]
好尴尬。。公司网络环境原因，图片没传上去。。。下面把图片转换成文字

bogon:greys ***$ echo $JAVA_HOME
/library/java/JavaVirtualMachines/jdk1.7.0_79.jdk/contents/home
bogon:greys ***$ ./greys.sh 3910
illegal ENV, please set $JAVA_HOME to JDK6+

**Comment by oldmanpushcart** [comment]
Hi 我看到你的`$JAVA_HOME`的路径设置

```
/library/java/JavaVirtualMachines/jdk1.7.0_79.jdk/contents/home
```
你的 $JAVA_HOME 设置的可能有问题，因为你的大小写可能存在错误。

贴下我的
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
```
