### ISSUE TITLE
wiki中的链接信息错误，希望更新wiki

### ISSUE THREAD

**Issue by douniwan5788** [oldmanpushcart/greys-anatomy#62]
wiki 中 `Installing` 的 `本地安装` 下的链接
>http://ompc.oss.aliyuncs.com/greys/greys-[VERSION].zip

描述不太清楚，使用http://ompc.oss.aliyuncs.com/greys/greys-1.7.0.4.zip 提示错误，应该是文件不存在。

`常见安装问题` 中的链接
>http://ompc.oss.aliyuncs.com/greys/greys.zip

字面和指向也不相符

**Comment by oldmanpushcart** [comment]
好的，马上修复

**Comment by oldmanpushcart** [comment]
已经修复了，谢谢提醒哈 :)
