### ISSUE TITLE
同一用户下多个jvm进程分别attach，实际attach的到都是同一个进程

### ISSUE THREAD

**Issue by zzycjcg** [oldmanpushcart/greys-anatomy#68]
使用版本是1.7.0.5
<650 linux32 [icore] : /home/icore/greys>./greys.sh 15650
ga?>jvm
+--------------------+-----------------------------------------------------------------------------------------------------+
|           CATEGORY | INFO                                                                                                |
+--------------------+-----------------------------------------------------------------------------------------------------+
|            RUNTIME |              MACHINE-NAME : 15650@linux32                                                           |

<652 linux32 [icore] : /home/icore/greys>./greys.sh 3969
ga?>jvm
+--------------------+-----------------------------------------------------------------------------------------------------+
|           CATEGORY | INFO                                                                                                |
+--------------------+-----------------------------------------------------------------------------------------------------+
|            RUNTIME |              MACHINE-NAME : 15650@linux32

**Comment by zzycjcg** [comment]
自己知道原因了：因为使用的是默认模式，每次端口都一样，连接到的是同一个jvm.
但问题来了：如何设定连接端口呢？

**Comment by oldmanpushcart** [comment]
嗯，这个确实交互上没做好，不能怪用户疑问。

选择端口这样的

```shell
greys.sh PID@IP:PORT
```

**Comment by zzycjcg** [comment]
谢谢答复！
嗯，这个我也知道。其实我想问的是，在有多个jvm进程的情况下，除了默认的3658可用，如何拿到其他的jvm监听port？

**Comment by oldmanpushcart** [comment]
这个需要加载的人告诉你，负责greys加载的人肯定知道自己分配的端口
