### ISSUE TITLE
能否提供离线安装版本？ 以及默认不自动更新？或者加上选项

### ISSUE THREAD

**Issue by yaojuncn** [oldmanpushcart/greys-anatomy#84]
你好，

有些网络环境连过来更新比较慢？ 而且有时候的确旧版本也够用了？
能否提供下载离线安装的版本？有些网络环境本身也连不了外网。。。

谢谢

**Comment by oldmanpushcart** [comment]
恩，有离线安装的脚本。

[本地安装](https://github.com/oldmanpushcart/greys-anatomy/wiki/Installing#%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85)

**Comment by yaojuncn** [comment]
多谢！

**Comment by oldmanpushcart** [comment]
大哥，和你商量个事呗。最近马上就要到双十一了，公司的事务繁忙，我估计要到双十一之后才能增加这个功能了。

我和对了下，greys.sh中指定的超时时间为5秒，即greys在启动过程中会有5秒的时间去尝试连接远程阿里云服务器检查最新的greys版本。如果你觉得5秒也忍受不住，可以先将greys中的

```shell
    update_if_necessary \
        || echo "update fail, ignore this update." 1>&2
```

这段代码注释掉，可以避免脚本启动自动更新。

**Comment by yaojuncn** [comment]
哥，你写这么好用的开源软件给大家用， 然后对用户还这么上心， 我感动极了！
我这需求也是随口一说，一点也不着急。 
你工作为重以后有空的时候搞吧。 

多谢！

**Comment by oldmanpushcart** [comment]
我在`greys.sh`中增加参数

```
# define update if necessary
# 0 : 不自动升级
# 1 : 自动升级（默认）
UPDATE_IF_NECESSARY=0
```
