### ISSUE TITLE
1.7.2.3版本使用sm出现问题

### ISSUE THREAD

**Issue by muyuqiu001** [oldmanpushcart/greys-anatomy#86]
____  ____ _____ _   _  ___ _____ _____ ____  _____ _| |_ ___  ____  _   _ 
 / _  |/ ___) ___ | | | |/___|_____|____ |  _ \(____ (_   _) _ \|    \| | | |
( (_| | |   | ____| |_| |___ |     / ___ | | | / ___ | | || |_| | | | | |_| |
 \___ |_|   |_____)\__  (___/      \_____|_| |_\_____|  \__)___/|_|_|_|\__  |
(_____|           (____/                                              (____/ 
                                              +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                                              |v|e|r|s|i|o|n|:|1|.|7|.|2|.|3|
                                              +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
ga?>sm -d org.apache.commons.lang.StringUtils
Command "sm" preprocessor failed : method-pattern argument was missing..

报以上的错误，是哪里的问题呢？

我发现程序那边抛出异常：
2015-11-18 14:41:36 [ga-command-execute-daemon] INFO  greys-anatomy - Command "sm" preprocessor failed : method-pattern argument was missing..
com.github.ompc.greys.core.exception.CommandException: java.lang.IllegalArgumentException: method-pattern argument was missing.
	at com.github.ompc.greys.core.command.Commands.newCommand(Commands.java:150) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.executeCommand(DefaultCommandHandler.java:86) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.GaServer$4.run(GaServer.java:329) [greys-core.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
Caused by: java.lang.IllegalArgumentException: method-pattern argument was missing.
	at com.github.ompc.greys.core.command.Commands.newCommand(Commands.java:135) ~[greys-core.jar:na]
	... 5 common frames omitted

需要的是方法加上参数？这样给的实际用例中是不是有问题啊？

**Comment by wildwolfk** [comment]
用help sm 看下吧

提示很清楚了 少了方法的匹配参数  

你如果不关心具体什么方法，可以写个 *

**Comment by oldmanpushcart** [comment]
确实不能怪用户，我之前的版本中的`method-pattern`参数默认给了一个`*`，但在后来某一次版本变更时手贱改了下，我记住了，下个版本给你恢复回来。

**Comment by muyuqiu001** [comment]
@oldmanpushcart 
还有啊，
com.github.ompc.greys.core.command.SearchClassCommand里面
@Cmd(name = "sc", sort = 0, summary = "Search all the classes loaded by JVM",
        eg = {
                "sc -E org\\.apache\\.commons\\.lang\\.StringUtils",
                "sc -d org.apache.commons.lang.StringUtils",
                "sc -Sd *StringUtils"
        })
是不是最后一行的提示的参数不对啊，不是-Sd，是-fd吧？

**Comment by muyuqiu001** [comment]
@oldmanpushcart 
请问另一个问题：
ga?>sm -d main *
+----------------+----------------+
| DECLARED-CLASS | VISIBLE-METHOD |
+----------------+----------------+
Affect(row-cnt:0) cost in 568 ms.

我搜索的main方法应该已经加载到内存中了吧，为什么不显示呢？

**Comment by oldmanpushcart** [comment]
## 第一个问题

```
是不是最后一行的提示的参数不对啊，不是-Sd，是-fd吧？
```

确实如你所说，`-S`的参数已经过时，我在`1.7.2.0`版本中已经去掉，但却忘记更改文案提示，我会在下一个版本纠正包括`sm`命令在内的其它过期的帮助信息。

## 第二个问题

```
我搜索的main方法应该已经加载到内存中了啊，为什么不显示呢？
```

`sm`命令的格式为

```
sm <类名匹配> <方法名匹配>
```

所以如果你希望搜索所有已加载到JVM类中所有的`main`方法，可以这样写`sm * main`

**Comment by muyuqiu001** [comment]
@oldmanpushcart 感谢回复，
突然感觉在提第二个问题的时候脑袋短路了。。。

**Comment by muyuqiu001** [comment]
![default](https://cloud.githubusercontent.com/assets/971514/11387366/aaddac14-9364-11e5-930a-bdf918f65547.JPG)

刚刚开始还是显示两个提示符啊？
ga?>
ga?>

@oldmanpushcart 和使用哪个shell有关系吗？

**Comment by muyuqiu001** [comment]
惊喜是这个？？

I will not make the same mistakes that you did
I will not let myself
Cause my heart so much misery
I will not break the way you did
You fell so hard

I ve learned the hard way
To never let it get that far

Because of you
I never stray too far from the sidewalk
Because of you
I learned to play on the safe side so I don t get hurt
Because of you
I find it hard to trust not only me, but everyone around me
Because of you
I am afraid

I lose my way
And it s not too long before you point it out
I cannot cry
Because you know that s weakness in your eyes
I m forced to fake
A smile, a laugh everyday of my life
My heart can't possibly break
When it wasn't even whole to start with

Because of you
I never stray too far from the sidewalk
Because of you
I learned to play on the safe side so I don t get hurt
Because of you
I find it hard to trust not only me, but everyone around me
Because of you
I am afraid

I watched you die
I heard you cry every night in your sleep
I was so young
You should have known better than to lean on me
You never thought of anyone else
You just saw your pain
And now I cry in the middle of the night
For the same damn thing

Because of you
I never stray too far from the sidewalk
Because of you
I learned to play on the safe side so I don t get hurt
Because of you
I try my hardest just to forget everything
Because of you
I don t know how to let anyone else in
Because of you
I m ashamed of my life because it s empty
Because of you
I am afraid

Because of you
Because of you
...

**Comment by muyuqiu001** [comment]
![default](https://cloud.githubusercontent.com/assets/971514/11391438/6933bb4a-938d-11e5-8015-e4aea6cf5d50.JPG)

这一块少拦截了一个异常吧？

**Comment by oldmanpushcart** [comment]
你是说少了`IllegalArgumentException`异常吧，当时有考虑过，因为这个异常的抛出条件是

```
     * @exception IllegalArgumentException  if the specified object is not an
     *              instance of the class or interface declaring the underlying
     *              field (or a subclass or implementor thereof),
     *              or if an unwrapping conversion fails.
```

这个我从编码上就应该规避这个异常，所以当时考虑了下所以没有拦他，不过从严谨的角度出发，应该拦的～ :) 我在下一个版本中加上

**Comment by muyuqiu001** [comment]
@oldmanpushcart 麻烦看下两个提示符的问题~开始运行的时候出来了两个提示符~

**Comment by oldmanpushcart** [comment]
这个我有点修复不掉～让我考虑考虑，现在还有一个groovy在perm区的泄漏还没解决

**Comment by muyuqiu001** [comment]
![default](https://cloud.githubusercontent.com/assets/971514/11490763/d984279e-9816-11e5-878b-f1db385aa2bd.PNG)
这个session如果map中存在的话，也没有主动销毁吧
@oldmanpushcart

**Comment by muyuqiu001** [comment]
![default](https://cloud.githubusercontent.com/assets/971514/11491944/b2cfb4b4-9821-11e5-8e8c-c5a6c8e4e480.PNG)

**Comment by oldmanpushcart** [comment]
catch不全和判断多余的问题，我都在`1.7.3.0`版本中修复了
