### ISSUE TITLE
使用stack命令显示的调用行数出现错误

### ISSUE THREAD

**Issue by muyuqiu001** [oldmanpushcart/greys-anatomy#90]
使用最新版本的1.7.3.0版本
调用stack命令的时候，显示如下
ga?>stack *TestMain buildEvent
Press Ctrl+D to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 1722 ms.
thread_name="main" thread_id=0x1;is_daemon=false;priority=5;
    @sun.reflect.DelegatingMethodAccessorImpl.invoke()
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.test.mytest.TestMain.buildEvent(TestMain.java:-1)
        at com.test.mytest.TestMain.main(TestMain.java:18)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

比如TestMain.java显示的调用位置为-1了，还有NativeMethodAccessorImpl.invoke0的行数位置为-2了

**Comment by oldmanpushcart** [comment]
收到，周末发版本修复这个BUG，非常抱歉

**Comment by oldmanpushcart** [comment]
在`1.7.3.1`版本已经修复

**Comment by muyuqiu001** [comment]
@oldmanpushcart 
这个问题是不是还是不对啊？

这个是我调试时取出的堆栈，使用Thread.currentThread().getStackTrace()得到的堆栈信息：
com.test.mytest.TestMain.buildEvent(TestMain.java)
com.test.mytest.TestMain.main(TestMain.java:18)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
java.lang.reflect.Method.invoke(Method.java:597)
org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
所以在使用stack的时候，打印出的buildEvent所在行数为-1，
通过tt -i 看某个index的堆栈信息是正确的~

**Comment by oldmanpushcart** [comment]
你的Test代码发来给我瞅瞅?

**Comment by muyuqiu001** [comment]
package com.test.greys;

public class TestMain
{
    private static TestMain Instance = new TestMain();
    
    public TestMain()
    {
        
    }

    public static void main(String[] args) throws InterruptedException
    {
        int time = 1;

        while (time <= 3600)
        {
            MyEvent myEvent = Instance.buildEvent(time, args[0]);
            System.out.println(myEvent);
            Thread.sleep(3000);
            time++;
        }

        System.out.println("end");
    }
    
    public MyEvent buildEvent(int time, String id)
    {
        MyEvent myEvent = new MyEvent();
        myEvent.setMyeventid(time);
        myEvent.setTimestamp(System.currentTimeMillis());
        myEvent.setId(id);
        
        return myEvent;
    }
}

**Comment by muyuqiu001** [comment]
需不需要新建一个issue：
当查询的东西返回输出内容比较多时，超过2048字节的时候，就挂死了，也不抛异常，必须重启原应用才生效，出现过一次，我也忘记当时使用什么命令了

**Comment by oldmanpushcart** [comment]
MyEvent的代码能否也提供下；

超过2048字节我自己特意测试过的，应该不会有问题，下次重现的时候麻烦dump下console和目标jvm的内存然后发给我 :)

**Comment by muyuqiu001** [comment]
````java
package com.test.greys;

public class Event
{
    long timestamp = 0L;

    String id = null;

    public Event()
    {
        
    }
    
    public long getTimestamp()
    {
        return timestamp;
    }

    public void setTimestamp(long timestamp)
    {
        this.timestamp = timestamp;
    }

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }
}
````
--------------
````java
package com.test.greys;

public class MyEvent extends Event
{
    int myeventid = 0;

    public MyEvent()
    {

    }

    public MyEvent(int myeventid, long timestamp)
    {
        this.myeventid = myeventid;
        this.timestamp = timestamp;
    }

    public int getMyeventid()
    {
        return myeventid;
    }

    public void setMyeventid(int myeventid)
    {
        this.myeventid = myeventid;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + myeventid;
        return result;
    }

    @Override
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        MyEvent other = (MyEvent) obj;
        if (myeventid != other.myeventid)
            return false;
        return true;
    }

    @Override
    public String toString()
    {
        return "MyEvent [myeventid=" + myeventid + ", timestamp=" + timestamp + ", id=" + id + "]";
    }
}
````

**Comment by oldmanpushcart** [comment]
```
ga?>stack *TestMain buildEvent
Press Ctrl+D to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 75 ms.
thread_name="main" thread_id=0x1;is_daemon=false;priority=5;
    @TestMain.buildEvent(TestMain.java:-1)
        at TestMain.main(TestMain.java:16)

ga?>
```

哦，我明白了。 `@TestMain.buildEvent(TestMain.java:-1)`，在`@`字符这一行的代表的是起始函数，之所以是`-1`是我的疏忽，其实这个值没有任何的意义，你可以忽略掉。


```
ga?>stack *MyEvent setId
Press Ctrl+D to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 36 ms.
thread_name="main" thread_id=0x1;is_daemon=false;priority=5;
    @Event.setId(Event.java:-1)
        at TestMain.buildEvent(TestMain.java:30)
        at TestMain.main(TestMain.java:16)

ga?>
```

让我考虑下，是否在下个版本中修复掉吧，问题不大。
