### ISSUE TITLE
怎么调试啊？

### ISSUE THREAD

**Issue by muyuqiu001** [oldmanpushcart/greys-anatomy#96]
有没有debug模式啊？好像都没办法调试

**Comment by oldmanpushcart** [comment]
> greys 怎么调试？初看都得打jar，不知道怎么调试代码。

JVM的调试是基于JDWP协议的，所以只要在JVM中跑的代码理论上你都能进行远程调试（比如JDB、Eclipse/IDEA的远程调试）。你所需要做的是

1. 将你的工程代码和Greys的代码都导入到同一个工作空间（Eclipse叫workspace；IDEA叫Project）中 
1. 在Java应用启动的时候增加参数 "-Xdebug -Xrunjdwp:transport=dt_socket,suspend=n,server=y,address=8000"，具体参数的含义可以Google到
1. 在Eclipse/IDEA中发起远程调试

至此，你将能对Greys的代码进行调试

**Comment by muyuqiu001** [comment]
这个我试过了，不知道是不是多次反射的原因，打的断点只能在GreysLauncher/AgentLauncher/GreysConsole上生效，比如在DefaultCommandHandler的executeCommand上打断点就是停不住

**Comment by oldmanpushcart** [comment]
好的，我周末核对下 :)

**Comment by oldmanpushcart** [comment]
Hi @muyuqiu001 

我周末用我的本地测试工程`AgentTest`进行了一次演示，是可以进行debug的哈。

- 以下是我的工程截图

  ![debug](https://raw.githubusercontent.com/oldmanpushcart/images/master/temp/063307243ccff2381e3898fa14163791.png)

**Comment by muyuqiu001** [comment]
我在windows下通过远程端口进行调试的，环境不一样的原因吗？

**Comment by oldmanpushcart** [comment]
我相信不是 :)

**Comment by muyuqiu001** [comment]
1、在greys.sh中添加debugMode
```shell
DEBUG_MODE="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000"
....
attach_jvm()
{
    local greys_lib_dir=${GREYS_LIB_DIR}/${1}/greys
    echo ${greys_lib_dir}

    if [ ${TARGET_IP} = ${DEFAULT_TARGET_IP} ]; then
        ${JAVA_HOME}/bin/java \
           ${BOOT_CLASSPATH} ${JVM_OPTS} ${DEBUG_MODE} \
            -jar ${greys_lib_dir}/greys-core.jar \
                -pid ${TARGET_PID} \
                -target ${TARGET_IP}":"${TARGET_PORT} \
                -core "${greys_lib_dir}/greys-core.jar" \
                -agent "${greys_lib_dir}/greys-agent.jar"
    fi
}
````
2、在eclipse中设置Remoting参数
![default](https://cloud.githubusercontent.com/assets/971514/11773909/e6c8a886-a26a-11e5-96a3-c1c6f74e9dfd.JPG)
3、在com.github.ompc.greys.core.server.DefaultCommandHandler的executeCommand方法中打上断点
![1](https://cloud.githubusercontent.com/assets/971514/11773939/3712ab34-a26b-11e5-9f4f-ab7248b552cf.JPG)
4、启动greys.sh

之后在打断点的地方停不住

**Comment by neweast** [comment]
@muyuqiu001 琨总的意思，应该是指，有一个应用A，首先以debug模式启动应用A；然后在idea或者eclipse里将greys作为一个maven模块，添加到应用A里；再通过idea或者eclips远程调试应用A；最后运行greys，pid为应用A的pid。这个时候应该就可以debug了。

**Comment by oldmanpushcart** [comment]
@neweast 啊哈，是这个意思。不过`然后在idea或者eclipse里将greys作为一个maven模块，添加到应用A里`，这个是我为乐图展示方便，所以才作为一个子模块加入进来，实际上greys可以独立一个工程而存在的。

我的对 @muyuqiu001 的建议是

> 你应该在目标JVM中加上`debug-mode`，否则你只能调试greys的控制台。

**Comment by muyuqiu001** [comment]
@neweast 按照你说的这么操作的话，会不会classloader将agent与core同时加载，由于在同一个classloader中，agent与core在运行的时候就会报错的吧？
现在我是将一个test工程在windows下打成jar包，然后在linux上通过java -jar test.jar进行执行的。

**Comment by muyuqiu001** [comment]
我直接将目标应用使用debug模式启动就可以进行调试了是吧？

**Comment by neweast** [comment]
@muyuqiu001 greys attach到目标JVM之后，目标JVM本身就会同时加载agent和core，他们俩应该没什么冲突吧。

**Comment by muyuqiu001** [comment]
@neweast 我刚刚的意思是将agent和core与目标工程打在同一个jar包中，然后使用java -jar 进行执行

**Comment by neweast** [comment]
@muyuqiu001 

或者你直接这样子吧：

1. 运行你的jar包。查下pid是多少。
2. grey.sh 监控目标pid
3. idea或者eclipse打开gryes的工程，远程调试连接到jar包的JVM。

**Comment by muyuqiu001** [comment]
可以调试了~
和上面讲的一样，debug目标进程就可以了~
谢谢各位~ @oldmanpushcart  @neweast

**Comment by zhenjia001** [comment]
@muyuqiu001 debug目标进程？能否帮忙解释一下，是指grey.sh pid,grey的进程还是监控的进程？
我也遇到了你前面遇到的问题，就是agent 里面都debug 断点不住，
